--------------------------------------------------------
--
--   S000: Erebus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 223;
   ypos = 1739;
   gov  = _G.GOV_CORPORATE;
   tech = 6;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_MINING;
}
