--------------------------------------------------------
--
--   S001: Quaris
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 118;
   ypos = 1844;
   gov  = _G.GOV_FEUDAL;
   tech = 4;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MILITARY;
}
