--------------------------------------------------------
--
--   S002: Talus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 419;
   ypos = 1892;
   gov  = _G.GOV_DEMOCRACY;
   tech = 6;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
