--------------------------------------------------------
--
--   S003: Gemini
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 684;
   ypos = 1917;
   gov  = _G.GOV_CORPORATE;
   tech = 6;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
