--------------------------------------------------------
--
--   S004: Apus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 565;
   ypos = 1758;
   gov  = _G.GOV_CORPORATE;
   tech = 5;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
