--------------------------------------------------------
--
--   S005: Ceti
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 367;
   ypos = 1632;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
