--------------------------------------------------------
--
--   S006: Caelum
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 130;
   ypos = 1592;
   gov  = _G.GOV_FEUDAL;
   tech = 5;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MINING;
}
