--------------------------------------------------------
--
--   S007: Serpens
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 523;
   ypos = 1527;
   gov  = _G.GOV_CORPORATE;
   tech = 10;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
