--------------------------------------------------------
--
--   S008: Atlia
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 309;
   ypos = 1368;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
