--------------------------------------------------------
--
--   S009: Vega
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 700;
   ypos = 1485;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_MRI;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
