--------------------------------------------------------
--
--   S010: Elysia
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 896;
   ypos = 1586;
   gov  = _G.GOV_DEMOCRACY;
   tech = 5;
   faction = _G.FACTION_ELYSIA;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
