--------------------------------------------------------
--
--   S011: Elea
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 877;
   ypos = 1732;
   gov  = _G.GOV_DEMOCRACY;
   tech = 3;
   faction = _G.FACTION_ELYSIA;
   industry = _G.INDUSTRY_AGRICULTURE;
}
