--------------------------------------------------------
--
--   S012: Degani
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1096;
   ypos = 1692;
   gov  = _G.GOV_DEMOCRACY;
   tech = 5;
   faction = _G.FACTION_DEGANI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
