--------------------------------------------------------
--
--   S013: Aquarius
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1278;
   ypos = 1809;
   gov  = _G.GOV_FEUDAL;
   tech = 2;
   faction = _G.FACTION_DEGANI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
