--------------------------------------------------------
--
--   S014: Navi
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1425;
   ypos = 1922;
   gov  = _G.GOV_ANARCHIC;
   tech = 3;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MILITARY;
}
