--------------------------------------------------------
--
--   S015: Icarus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1589;
   ypos = 1809;
   gov  = _G.GOV_ANARCHIC;
   tech = 2;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MINING;
}
