--------------------------------------------------------
--
--   S016: Lepus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1232;
   ypos = 1629;
   gov  = _G.GOV_DEMOCRACY;
   tech = 2;
   faction = _G.FACTION_DEGANI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
