--------------------------------------------------------
--
--   S017: Tucana
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1377;
   ypos = 1553;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 5;
   faction = _G.FACTION_KECK;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
