--------------------------------------------------------
--
--   S018: Virgo
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1575;
   ypos = 1637;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 1;
   faction = _G.FACTION_KECK;
   industry = _G.INDUSTRY_AGRICULTURE;
}
