--------------------------------------------------------
--
--   S019: Sirius
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1773;
   ypos = 1740;
   gov  = _G.GOV_ANARCHIC;
   tech = 5;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MILITARY;
}
