--------------------------------------------------------
--
--   S020: Altair
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1478;
   ypos = 1730;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 3;
   faction = _G.FACTION_KECK;
   industry = _G.INDUSTRY_MINING;
}
