--------------------------------------------------------
--
--   S021: Alpha Centauri
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 804;
   ypos = 1377;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
