--------------------------------------------------------
--
--   S022: Terra
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 851;
   ypos = 1244;
   gov  = _G.GOV_CORPORATE;
   tech = 10;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
