--------------------------------------------------------
--
--   S023: Polaris
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1069;
   ypos = 1487;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_AGRICULTURE;
}
