--------------------------------------------------------
--
--   S024: Beta Centauri
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 655;
   ypos = 1294;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_MINING;
}
