--------------------------------------------------------
--
--   S025: Orion
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 629;
   ypos = 1130;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
