--------------------------------------------------------
--
--   S026: Lupus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 761;
   ypos = 990;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_AGRICULTURE;
}
