--------------------------------------------------------
--
--   S027: Aquila
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 979;
   ypos = 1032;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_MILITARY;
}
