--------------------------------------------------------
--
--   S028: Ramses
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1089;
   ypos = 1281;
   gov  = _G.GOV_CORPORATE;
   tech = 8;
   faction = _G.FACTION_LUMINA;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
