--------------------------------------------------------
--
--   S029: Circinus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 326;
   ypos = 1194;
   gov  = _G.GOV_FEUDAL;
   tech = 2;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_MINING;
}
