--------------------------------------------------------
--
--   S030: Fornax
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 471;
   ypos = 1044;
   gov  = _G.GOV_CORPORATE;
   tech = 10;
   faction = _G.FACTION_CYTECH;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
