--------------------------------------------------------
--
--   S031: Castor
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 222;
   ypos = 997;
   gov  = _G.GOV_CORPORATE;
   tech = 9;
   faction = _G.FACTION_CYTECH;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
