--------------------------------------------------------
--
--   S032: Perseus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 202;
   ypos = 873;
   gov  = _G.GOV_CORPORATE;
   tech = 9;
   faction = _G.FACTION_CYTECH;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
