--------------------------------------------------------
--
--   S033: Indus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 551;
   ypos = 920;
   gov  = _G.GOV_CORPORATE;
   tech = 8;
   faction = _G.FACTION_TRIDENT;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
