--------------------------------------------------------
--
--   S034: Auriga
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 335;
   ypos = 796;
   gov  = _G.GOV_CORPORATE;
   tech = 8;
   faction = _G.FACTION_CYTECH;
   industry = _G.INDUSTRY_MINING;
}
