--------------------------------------------------------
--
--   S035: Electra
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 222;
   ypos = 667;
   gov  = _G.GOV_CORPORATE;
   tech = 8;
   faction = _G.FACTION_CYTECH;
   industry = _G.INDUSTRY_MILITARY;
}
