--------------------------------------------------------
--
--   S036: Sagitta
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 307;
   ypos = 563;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 5;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_MINING;
}
