--------------------------------------------------------
--
--   S037: Lacerta
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 620;
   ypos = 628;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 7;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_MILITARY;
}
