--------------------------------------------------------
--
--   S038: Vortraag
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 580;
   ypos = 719;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 7;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
