--------------------------------------------------------
--
--   S039: Taurus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 696;
   ypos = 804;
   gov  = _G.GOV_CORPORATE;
   tech = 8;
   faction = _G.FACTION_TRIDENT;
   industry = _G.INDUSTRY_MILITARY;
}
