--------------------------------------------------------
--
--   S040: Leo
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 932;
   ypos = 846;
   gov  = _G.GOV_CORPORATE;
   tech = 9;
   faction = _G.FACTION_TRIDENT;
   industry = _G.INDUSTRY_MILITARY;
}
