--------------------------------------------------------
--
--   S041: Aries
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1068;
   ypos = 933;
   gov  = _G.GOV_CORPORATE;
   tech = 10;
   faction = _G.FACTION_TRIDENT;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
