--------------------------------------------------------
--
--   S042: Quesada
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1213;
   ypos = 1145;
   gov  = _G.GOV_DEMOCRACY;
   tech = 9;
   faction = _G.FACTION_QUESADANS;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
