--------------------------------------------------------
--
--   S043: Megreb
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 634;
   ypos = 475;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 5;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_MILITARY;
}
