--------------------------------------------------------
--
--   S044: Eridanus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 751;
   ypos = 394;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 5;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_MILITARY;
}
