--------------------------------------------------------
--
--   S045: Zaurak
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 741;
   ypos = 253;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 3;
   faction = _G.FACTION_VORTRAAG;
   industry = _G.INDUSTRY_MILITARY;
}
