--------------------------------------------------------
--
--   S046: Nashira
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 496;
   ypos = 329;
   gov  = _G.GOV_ANARCHIC;
   tech = 4;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MILITARY;
}
