--------------------------------------------------------
--
--   S047: Procyon
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 298;
   ypos = 305;
   gov  = _G.GOV_ANARCHIC;
   tech = 1;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_AGRICULTURE;
}
