--------------------------------------------------------
--
--   S048: Sargon
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 461;
   ypos = 165;
   gov  = _G.GOV_ANARCHIC;
   tech = 4;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MINING;
}
