--------------------------------------------------------
--
--   S049: Azha
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 191;
   ypos = 117;
   gov  = _G.GOV_ANARCHIC;
   tech = 9;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MILITARY;
}
