--------------------------------------------------------
--
--   S050: Vela
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 835;
   ypos = 167;
   gov  = _G.GOV_ANARCHIC;
   tech = 3;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
