--------------------------------------------------------
--
--   S051: Nornes
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 950;
   ypos = 91;
   gov  = _G.GOV_ANARCHIC;
   tech = 1;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_AGRICULTURE;
}
