--------------------------------------------------------
--
--   S052: Grus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1235;
   ypos = 155;
   gov  = _G.GOV_ANARCHIC;
   tech = 4;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MILITARY;
}
