--------------------------------------------------------
--
--   S053: Medusa
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1336;
   ypos = 298;
   gov  = _G.GOV_ANARCHIC;
   tech = 6;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MILITARY;
}
