--------------------------------------------------------
--
--   S054: Acheron
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1512;
   ypos = 293;
   gov  = _G.GOV_ANARCHIC;
   tech = 1;
   faction = 0;
   industry = 0;
}
