--------------------------------------------------------
--
--   S055: Gorgon
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1542;
   ypos = 150;
   gov  = _G.GOV_ANARCHIC;
   tech = 6;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MINING;
}
