--------------------------------------------------------
--
--   S056: Typhon
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1750;
   ypos = 207;
   gov  = _G.GOV_ANARCHIC;
   tech = 9;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MILITARY;
}
