--------------------------------------------------------
--
--   S057: Hades
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1883;
   ypos = 383;
   gov  = _G.GOV_ANARCHIC;
   tech = 5;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MINING;
}
