--------------------------------------------------------
--
--   S058: Gehenna
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1844;
   ypos = 123;
   gov  = _G.GOV_ANARCHIC;
   tech = 10;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MILITARY;
}
