--------------------------------------------------------
--
--   S059: Solis
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1139;
   ypos = 350;
   gov  = _G.GOV_ANARCHIC;
   tech = 2;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MINING;
}
