--------------------------------------------------------
--
--   S060: Gomorrah
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1385;
   ypos = 497;
   gov  = _G.GOV_ANARCHIC;
   tech = 7;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
