--------------------------------------------------------
--
--   S061: Musca
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1593;
   ypos = 477;
   gov  = _G.GOV_ANARCHIC;
   tech = 7;
   faction = _G.FACTION_SOULLESS;
   industry = _G.INDUSTRY_MILITARY;
}
