--------------------------------------------------------
--
--   S062: Scorpio
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1289;
   ypos = 661;
   gov  = _G.GOV_ANARCHIC;
   tech = 4;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MILITARY;
}
