--------------------------------------------------------
--
--   S063: Carinox
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1615;
   ypos = 724;
   gov  = _G.GOV_ANARCHIC;
   tech = 3;
   faction = _G.FACTION_PIRATES;
   industry = _G.INDUSTRY_MINING;
}
