--------------------------------------------------------
--
--   S064: Plasmia
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1359;
   ypos = 839;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 8;
   faction = _G.FACTION_PLASMIDS;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
