--------------------------------------------------------
--
--   S065: Libra
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1115;
   ypos = 677;
   gov  = _G.GOV_CORPORATE;
   tech = 7;
   faction = _G.FACTION_TRIDENT;
   industry = _G.INDUSTRY_MINING;
}
