--------------------------------------------------------
--
--   S066: Krystallus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 910;
   ypos = 598;
   gov  = _G.GOV_FEUDAL;
   tech = 1;
   faction = _G.FACTION_KRYSTALLI;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
