--------------------------------------------------------
--
--   S067: Hydra
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1719;
   ypos = 862;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 3;
   faction = _G.FACTION_PLASMIDS;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
