--------------------------------------------------------
--
--   S068: Delphinus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1555;
   ypos = 926;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 5;
   faction = _G.FACTION_PLASMIDS;
   industry = _G.INDUSTRY_MINING;
}
