--------------------------------------------------------
--
--   S069: Pegasus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1692;
   ypos = 1054;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 3;
   faction = _G.FACTION_PLASMIDS;
   industry = _G.INDUSTRY_AGRICULTURE;
}
