--------------------------------------------------------
--
--   S070: Regulus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1731;
   ypos = 1196;
   gov  = _G.GOV_DEMOCRACY;
   tech = 4;
   faction = _G.FACTION_QUESADANS;
   industry = _G.INDUSTRY_INDUSTRIAL;
}
