--------------------------------------------------------
--
--   S071: Theseus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1865;
   ypos = 1298;
   gov  = _G.GOV_DEMOCRACY;
   tech = 3;
   faction = _G.FACTION_QUESADANS;
   industry = _G.INDUSTRY_MINING;
}
