--------------------------------------------------------
--
--   S072: Pleione
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1778;
   ypos = 1461;
   gov  = _G.GOV_FEUDAL;
   tech = 2;
   faction = _G.FACTION_JAHRWOXI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
