--------------------------------------------------------
--
--   S073: Keck
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1266;
   ypos = 1440;
   gov  = _G.GOV_DICTATORSHIP;
   tech = 6;
   faction = _G.FACTION_KECK;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
