--------------------------------------------------------
--
--   S074: Cygnus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1287;
   ypos = 1311;
   gov  = _G.GOV_FEUDAL;
   tech = 3;
   faction = _G.FACTION_JAHRWOXI;
   industry = _G.INDUSTRY_MINING;
}
