--------------------------------------------------------
--
--   S075: Jahrwox
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1467;
   ypos = 1260;
   gov  = _G.GOV_FEUDAL;
   tech = 5;
   faction = _G.FACTION_JAHRWOXI;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
