--------------------------------------------------------
--
--   S076: Corvus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1545;
   ypos = 1404;
   gov  = _G.GOV_FEUDAL;
   tech = 4;
   faction = _G.FACTION_JAHRWOXI;
   industry = _G.INDUSTRY_AGRICULTURE;
}
