--------------------------------------------------------
--
--   S077: Lyra
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1498;
   ypos = 1167;
   gov  = _G.GOV_DEMOCRACY;
   tech = 6;
   faction = _G.FACTION_QUESADANS;
   industry = _G.INDUSTRY_ADMINISTRATIVE;
}
