--------------------------------------------------------
--
--   S078: Cepheus
--
-- This file is autogenerated by <StarmapEditor.exe>
--

return {
   xpos = 1357;
   ypos = 1072;
   gov  = _G.GOV_DEMOCRACY;
   tech = 6;
   faction = _G.FACTION_QUESADANS;
   industry = _G.INDUSTRY_AGRICULTURE;
}
