--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest"


local quest = Quest {

   id                 = "Q000";
   log_text           = "[Q000_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q000a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S000=true,T003=true};

   preconditions = {
			};

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T002=true};
                 text            = "[Q000_1_0_MSG]";
                 log_text		= "[Q000_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T003=true};
                 log_text		= "[Q000_2_0_LOG]";
                 end_convo       = "Conv_Q000b";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
				 ACTIONS.give_experience{amount = 5, show=true},
                 ACTIONS.unlock_quest {quest="Q001", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
