--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest"


local quest = Quest {

   id                 = "Q001";
   log_text           = "[Q001_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 7;
   start_convo        = "Conv_Q001a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S000=true,T003=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T005=true};
                 text            = "[Q001_1_0_MSG]";
                 log_text		= "[Q001_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T007=true};
                 text            = "[Q001_2_0_MSG]";
                 log_text		= "[Q001_2_0_LOG]";
                 end_convo       = "Conv_Q001b";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T004=true};
                 text            = "[Q001_3_0_MSG]";
                 log_text		= "[Q001_3_0_LOG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T006=true};
                 text            = "[Q001_4_0_MSG]";
                 log_text		= "[Q001_4_0_LOG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE04";
                 location        = {S000=true,T006=true};
                 action			= "[Q001_5_0_ACTN]";
                 log_text		= "[Q001_5_0_LOG]";
                 conversation    = "Conv_Q001c";
                 end_text        = "[Q001_5_0_ENDMSG]";
                 next_state      = 6;
              },
           };
      [6]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T003=true};
                 log_text		= "[Q001_6_0_LOG]";
                 end_convo       = "Conv_Q001d";
                 next_state      = 7;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [7]={
                 ACTIONS.give_experience {amount=10, show=true},
                 ACTIONS.give_gold {amount=200, show=true},
                 ACTIONS.unlock_quest {quest="Q002", show=false},
				 ACTIONS.unlock_quest {quest="Q30a", show=false},
                 ACTIONS.give_item {item="I015", show=true},
                 ACTIONS.give_faction_status {faction="13", amount=-5, show=false},
                 ACTIONS.give_faction_status {faction="2", amount=5, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
