--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q002";
   log_text           = "[Q002_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q002a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S000=true,T003=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T002=true};
                 log_text		= "[Q002_1_0_LOG]";
                 end_text        = "[Q002_1_0_ENDMSG]";
                 end_convo       = "Conv_Q002b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE03";
                 location        = {S000=true,T002=true};
                 action			= "[Q002_2_0_ACTN]";
                 log_text		= "[Q002_2_0_LOG]";
                 conversation    = "Conv_Q002c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T003=true};
                 log_text		= "[Q002_3_0_LOG]";
                 end_convo       = "Conv_Q002d";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=15, show=true},
                 ACTIONS.give_gold {amount=250, show=true},
                 ACTIONS.unlock_quest {quest="Q003", show=false},
                 ACTIONS.give_faction_status {faction="2", amount=5, show=false},
                 ACTIONS.give_faction_status {faction="13", amount=-5, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
