--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q003";
   log_text           = "[Q003_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = true;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q003a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S000=true,T003=true};

   preconditions = {
      [1]={
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T004=true};
                 log_text		= "[Q003_1_0_LOG]";
                 end_convo       = "Conv_Q003b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B006";
                 monster         = "T004";
                 location        = {S000=true,T004=true};
                 action			= "[Q003_2_0_ACTN]";
                 log_text		= "[Q003_2_0_LOG]";
                 end_convo       = "Conv_Q003c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S000=true,T003=true};
                 log_text		= "[Q003_3_0_LOG]";
                 end_convo       = "Conv_Q003d";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=15, show=true},
                 ACTIONS.give_gold {amount=250, show=true},
                 ACTIONS.unlock_quest {quest="Q004", show=false},
                 ACTIONS.give_friend {friend="C003", show=true},
                 ACTIONS.unlock_quest {quest="Q0LA", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
