--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q004";
   log_text           = "[Q004_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 5;
   start_convo        = "Conv_Q004a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S000=true,T003=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S000=true,J002=true};
                 action			= "[Q004_1_0_ACTN]";
                 log_text		= "[Q004_1_0_LOG]";
                 conversation    = "Conv_Q004b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S000=true,J002=true};
                 action			= "[Q004_2_0_ACTN]";
                 log_text		= "[Q004_2_0_LOG]";
                 conversation    = "Conv_Q004c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S000=true,T003=true};
                 action			= "[Q004_3_0_ACTN]";
                 log_text		= "[Q004_3_0_LOG]";
                 conversation    = "Conv_Q004d";
                 end_text        = "[Q004_3_0_ENDMSG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B002";
                 monster         = "J002";
                 location        = {S000=true,J002=true};
                 action			= "[Q004_4_0_ACTN]";
                 log_text		= "[Q004_4_0_LOG]";
                 conversation    = "Conv_Q004e";
                 end_convo       = "Conv_Q004f";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.unlock_quest {quest="Q010", show=false},
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.give_gold {amount=250, show=true},
                 ACTIONS.give_friend {friend="C002", show=true},
                 ACTIONS.give_friend {friend="C005", show=true},
                 ACTIONS.unlock_quest {quest="Q0S0", show=false},
                 ACTIONS.unlock_quest {quest="Q0EA", show=false},
                 ACTIONS.show_cutscene {cutscene="CS2"},
          };
   };

   abandon_actions = {
   };

}

return quest
