--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q010";
   log_text           = "[Q010_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q010a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S000=true,J002=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B002";
                 monster         = "J001";
                 location        = {S000=true,J001=true};
                 action			= "[Q010_1_0_ACTN]";
                 log_text		= "[Q010_1_0_LOG]";
                 end_convo       = "Conv_Q010b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location_event {
                 location        = {S002=true,J003=true};
                 log_text		= "[Q010_2_0_LOG]";
                 end_convo       = "Conv_Q010c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B002";
                 monster         = "J003";
                 location        = {S002=true,J003=true};
                 action			= "[Q010_3_0_ACTN]";
                 log_text		= "[Q010_3_0_LOG]";
                 end_convo       = "Conv_Q010d";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
                 ACTIONS.unlock_quest {quest="Q0SA", show=false},
                 ACTIONS.hide_location {location="J001", show=false},
   };

   end_actions = {
      [3]={
                 ACTIONS.hide_location {location="J003", show=false},
           };
      [4]={
                 ACTIONS.unlock_quest {quest="Q011", show=false},
                 ACTIONS.give_experience {amount=20, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
