--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q011";
   log_text           = "[Q011_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 5;
   start_convo        = "Conv_Q011a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S002=true,J003=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S003=true,T046=true};
                 log_text		= "[Q011_1_0_LOG]";
                 end_convo       = "Conv_Q011b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S003=true,T046=true};
                 text            = "[Q011_2_0_MSG]";
                 action			= "[Q011_2_0_ACTN]";
                 log_text		= "[Q011_2_0_LOG]";
                 end_convo       = "Conv_Q011c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T046=true};
                 action			= "[Q011_3_0_ACTN]";
                 log_text		= "[Q011_3_0_LOG]";
                 end_convo       = "Conv_Q011d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T045=true};
                 action			= "[Q011_4_0_ACTN]";
                 log_text		= "[Q011_4_0_LOG]";
                 end_convo       = "Conv_Q011e";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.unlock_quest {quest="Q01B", show=false},
                 ACTIONS.give_experience {amount=30, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
