--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q012";
   log_text           = "[Q012_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q012a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S003=true,T046=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S003=true,J022=true};
                 action			= "[Q012_1_0_ACTN]";
                 log_text		= "[Q012_1_0_LOG]";
                 end_convo       = "Conv_Q012c";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,J014=true};
                 action			= "[Q012_1_1_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T045=true};
                 action			= "[Q012_1_2_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T042=true};
                 action			= "[Q012_1_3_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T044=true};
                 action			= "[Q012_1_4_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T043=true};
                 action			= "[Q012_1_5_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,J003=true};
                 action			= "[Q012_1_6_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T013=true};
                 action			= "[Q012_1_7_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 1;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S011=true,J021=true};
                 log_text		= "[Q012_2_0_LOG]";				 
                 action			= "[Q012_2_0_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T047=true};
                 action			= "[Q012_2_1_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T049=true};
                 action			= "[Q012_2_2_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T051=true};
                 action			= "[Q012_2_3_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T050=true};
                 action			= "[Q012_2_4_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,J019=true};
                 action			= "[Q012_2_5_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T048=true};
                 action			= "[Q012_2_6_ACTN]";
                 log_text		= "[Q012_2_6_LOG]";
                 end_convo       = "Conv_Q012d";
                 next_state      = 3;
              },
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T324=true};
                 action			= "[Q012_2_7_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 2;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T048=true};
                 action			= "[Q012_3_0_ACTN]";
                 log_text		= "[Q012_3_0_LOG]";
                 end_convo       = "Conv_Q012e";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.unlock_quest {quest="Q013", show=false},
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.give_gold {amount=250, show=true},
                 ACTIONS.unlock_quest {quest="Q01C", show=false},
                 ACTIONS.unlock_quest {quest="Q0D0", show=false},
                 ACTIONS.unlock_quest {quest="Q0D3", show=false},
                 ACTIONS.unlock_quest {quest="Q0D4", show=false},
                 ACTIONS.unlock_quest {quest="Q0D5", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
