--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q013";
   log_text           = "[Q013_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q013a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S011=true,T048=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S011=true,T050=true};		 
                 end_convo       = "Conv_Q013b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE06";
                 location        = {S011=true,T050=true};
                 action			= "[Q013_2_0_ACTN]";
                 log_text		= "[Q013_2_0_LOG]";
                 end_convo       = "Conv_Q013c";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.unlock_quest {quest="Q01A", show=false},
                 ACTIONS.give_experience {amount=30, show=true},
                 ACTIONS.give_gold {amount=500, show=true},
                 ACTIONS.unlock_quest {quest="Q0PA", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
