--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q014";
   log_text           = "[Q014_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 7;
   start_convo        = "Conv_Q014a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S011=true,T048=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T055=true};
                 action			= "[Q014_1_0_ACTN]";
                 log_text		= "[Q014_1_0_LOG]";
                 end_convo       = "Conv_Q014b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE04";
                 location        = {S010=true,T056=true};
                 action			= "[Q014_2_0_ACTN]";
                 log_text		= "[Q014_2_0_LOG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE06";
                 location        = {S010=true,T056=true};
                 action			= "[Q014_3_0_ACTN]";
                 log_text		= "[Q014_3_0_LOG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T055=true};
                 action			= "[Q014_4_0_ACTN]";
                 log_text		= "[Q014_4_0_LOG]";
                 end_convo       = "Conv_Q014c";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S023=true,T106=true};
                 action			= "[Q014_5_0_ACTN]";
                 log_text		= "[Q014_5_0_LOG]";				 
                 end_convo       = "Conv_Q014d";
                 next_state      = 6;
              },
              OBJECTIVES.go_to_location {
                 location        = {S023=true,T108=true};
                 action			= "[Q014_5_1_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 5;
              },
              OBJECTIVES.go_to_location {
                 location        = {S023=true,J035=true};
                 action			= "[Q014_5_2_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 5;
              },
              OBJECTIVES.go_to_location {
                 location        = {S023=true,J013=true};
                 action			= "[Q014_5_3_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 5;
              },
              OBJECTIVES.go_to_location {
                 location        = {S023=true,J034=true};
                 action			= "[Q014_5_4_ACTN]";
                 end_convo       = "Conv_Q012b";
                 next_state      = 5;
              },
           };
      [6]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE43";
                 location        = {S023=true,T106=true};
                 action			= "[Q014_6_0_ACTN]";
                 log_text		= "[Q014_6_0_LOG]";
                 end_convo       = "Conv_Q014e";
                 next_state      = 7;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [7]={
                 ACTIONS.unlock_quest {quest="Q015", show=false},
                 ACTIONS.give_experience {amount=100, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
