--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q015";
   log_text           = "[Q015_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q015a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S023=true,T106=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S073=true,T315=true};
                 log_text		= "[Q015_1_0_LOG]";
                 end_convo       = "Conv_Q015b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T315=true};
                 action			= "[Q015_2_0_ACTN]";
                 log_text		= "[Q015_2_0_LOG]";
                 end_convo       = "Conv_Q015c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T118=true};
                 action			= "[Q015_3_0_ACTN]";
                 log_text		= "[Q015_3_0_LOG]";
                 end_convo       = "Conv_Q015d";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.unlock_quest {quest="Q016", show=false},
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.show_cutscene {cutscene="CS3"},
          };
   };

   abandon_actions = {
   };

}

return quest
