--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q017";
   log_text           = "[Q017_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 9;
   start_convo        = "Conv_Q017a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S074=true,T137=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S075=true,T140=true};
				 log_text		= "[Q017_1_0_LOG]";
                 end_convo       = "Conv_Q017b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q017_2_0_ACTN]";
                 log_text		= "[Q017_2_0_LOG]";
                 end_convo       = "Conv_Q017c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q017_3_0_ACTN]";
                 log_text		= "[Q017_3_0_LOG]";
                 end_convo       = "Conv_Q017d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location_event {
                 location        = {S073=true,T118=true};
				 log_text		 = "[Q017_4_0_LOG]";
                 end_convo       = "Conv_Q017e";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T118=true};
                 action			= "[Q017_5_0_ACTN]";
                 log_text		= "[Q017_5_0_LOG]";
                 end_convo       = "Conv_Q017f";
                 next_state      = 6;
              },
           };
      [6]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T120=true};
                 action			= "[Q017_6_0_ACTN]";
                 log_text		= "[Q017_6_0_LOG]";
                 end_convo       = "Conv_Q017g";
                 next_state      = 7;
              },
           };
      [7]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE32";
                 location        = {S073=true,T315=true};
                 action			= "[Q017_7_0_ACTN]";
                 log_text		= "[Q017_7_0_LOG]";
                 end_convo       = "Conv_Q017h";
                 next_state      = 8;
              },
           };
      [8]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q017_8_0_ACTN]";
                 log_text		= "[Q017_8_0_LOG]";
                 end_convo       = "Conv_Q017i";
                 next_state      = 9;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [9]={
                 ACTIONS.unlock_quest {quest="Q018", show=false},
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.unlock_quest {quest="Q0E0", show=false},
                 ACTIONS.unlock_quest {quest="Q0E2", show=false},
                 ACTIONS.unlock_quest {quest="Q0E3", show=false},
                 ACTIONS.unlock_quest {quest="Q0J0", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
