--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q018";
   log_text           = "[Q018_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 7;
   start_convo        = "Conv_Q018a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S075=true,T140=true};

   preconditions = {
      [2]={
      CONDITIONS.min_gold {amount=500, text="[Q018_2_0_PRE]"},
           };
      [3]={
      CONDITIONS.min_gold {amount=500, text="[Q018_3_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S078=true,T153=true};
                 action			= "[Q018_1_0_ACTN]";
                 log_text		= "[Q018_1_0_LOG]";
                 end_text        = "[Q018_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S032=true,T176=true};
                 action			= "[Q018_2_0_ACTN]";
                 log_text		= "[Q018_2_0_LOG]";
                 end_text        = "[Q018_2_0_ENDMSG]";
                 end_convo       = "Conv_Q018b";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S077=true,J061=true};
                 action			= "[Q018_3_0_ACTN]";
                 log_text		= "[Q018_3_0_LOG]";
                 end_text        = "[Q018_3_0_ENDMSG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S077=true,J061=true};
                 action			= "[Q018_4_0_ACTN]";
                 log_text		= "[Q018_4_0_LOG]";
                 end_text        = "[Q018_4_0_ENDMSG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S077=true,J061=true};
                 action			= "[Q018_5_0_ACTN]";
                 log_text		= "[Q018_5_0_LOG]";
                 end_convo       = "Conv_Q018c";
                 next_state      = 6;
              },
           };
      [6]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE38";
                 location        = {S077=true,J061=true};
                 action			= "[Q018_6_0_ACTN]";
                 log_text		= "[Q018_6_0_LOG]";
                 conversation    = "Conv_Q018d";
                 end_convo       = "Conv_Q018e";
                 next_state      = 7;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_gold {amount=-500, show=false},
           };
      [3]={
                 ACTIONS.give_gold {amount=-500, show=false},
           };
      [7]={
                 ACTIONS.unlock_quest {quest="Q020", show=false},
                 ACTIONS.give_experience {amount=100, show=true},
                 ACTIONS.unlock_quest {quest="Q01D", show=false},
                 ACTIONS.show_cutscene {cutscene="CS4"},
          };
   };

   abandon_actions = {
   };

}

return quest
