--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q01A";
   log_text           = "[Q01A_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q01Aa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S011=true,T050=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T065=true};
                 action			= "[Q01A_1_0_ACTN]";
                 log_text		= "[Q01A_1_0_LOG]";
                 end_convo       = "Conv_Q01Ab";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B008";
                 monster         = "T065";
                 location        = {S012=true,T065=true};
                 action			= "[Q01A_2_0_ACTN]";
                 log_text		= "[Q01A_2_0_LOG]";
                 end_convo       = "Conv_Q01Ac";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S011=true,T048=true};
                 log_text		= "[Q01A_3_0_LOG]";
                 end_text        = "[Q01A_3_0_ENDMSG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_friend {friend="C004", show=true},
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.unlock_quest {quest="Q014", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
