--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest"


local quest = Quest {

   id                 = "Q01B";
   log_text           = "[Q01B_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q01Ba";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S003=true,T045=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S003=true,T046=true};
                 text            = "[Q01B_1_0_MSG]";
                 action			= "[Q01B_1_0_ACTN]";
                 log_text		= "[Q01B_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
      		OBJECTIVES.encounter_battle {
                 battleground    = "B010";
                 monster         = "I022";
                 location        = {S003=true,T013=true};
                 action			= "[Q01B_2_0_ACTN]";
                 log_text		= "[Q01B_2_0_ACTN]";--[Q01B_2_0_LOG]--using action removes location name from quest log
                 conversation    = "Conv_Q01Bb";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
                 ACTIONS.give_item {item="PI022", show=false},
   };

   end_actions = {
      [2]={
		  		 ACTIONS.give_resource {resource="9", amount=11, show=true},
      			 ACTIONS.give_resource {resource="4", amount=7, show=true},
                 ACTIONS.give_resource {resource="2", amount=4, show=true},
           };
      [3]={
                 ACTIONS.unlock_quest {quest="Q012", show=false},
                 ACTIONS.give_friend {friend="C000", show=true},
                 ACTIONS.give_experience {amount=25, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
