--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q01C";
   log_text           = "[Q01C_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S011=true,T048=true};

   preconditions = {
      [2]={
      CONDITIONS.max_resource {resource="12", amount=2, text="[Q01C_2_0_PRE]"},
           };
      [4]={
      CONDITIONS.min_resource {resource="2", amount=20, text="[Q01C_4_0_PRE]"},
      CONDITIONS.min_resource {resource="5", amount=20, text="[Q01C_4_1_PRE]"},
      CONDITIONS.min_resource {resource="4", amount=20, text="[Q01C_4_2_PRE]"},
      CONDITIONS.max_resource {resource="12", amount=2, text="[Q01C_3_0_PRE]"},
           };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S011=true,T051=true};
                 log_text		 = "[Q01C_1_0_LOG]";				 
                 text            = "[Q01C_1_0_MSG]";			 
                 action			 = "[Q01C_1_0_ACTN]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B006";
                 monster         = "T051";
                 location        = {S011=true,T051=true};
                 action			= "[Q01C_2_0_ACTN]";
                 log_text		= "[Q01C_2_0_LOG]";
                 end_text        = "[Q01C_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T048=true};
                 action			= "[Q01C_3_0_ACTN]";
                 log_text		= "[Q01C_3_0_LOG]";
                 end_text        = "[Q01C_3_0_ENDMSG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
                 ACTIONS.show_location {location="T051", show=false},
   };

   end_actions = {
      [4]={
      			ACTIONS.remove_resource {resource="5", amount=-20, show=false},
                 ACTIONS.remove_resource {resource="2", amount=-20, show=false},
                 ACTIONS.remove_resource {resource="4", amount=-20, show=false},
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.give_item {item="SMPA", show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
