--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q01D";
   log_text           = "[Q01D_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 3;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "[Q01D_STARTMSG]";
   incomplete_message = "";
   start_locations = {S077=true,J061=true};

   preconditions = {
      [3]={
      CONDITIONS.max_resource {resource="12", amount=2, text="[Q01D_2_0_PRE]"},--This precondition text is not quest specific
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S077=true,T155=true};
                 text            = "[Q01D_1_0_MSG]";
                 action			= "[Q01D_1_0_ACTN]";
                 log_text		= "[Q01D_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S077=true,T155=true};
                 text            = "[Q01D_2_0_MSG]";
                 action			= "[Q01D_2_0_ACTN]";
                 log_text		= "[Q01D_2_0_LOG]";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_item {item="STWS", show=true},
                 ACTIONS.give_experience {amount=40, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
