--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q020";
   log_text           = "[Q020_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 6;
   start_convo        = "Conv_Q020a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S077=true,J061=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S042=true,T114=true};
                 log_text		= "[Q020_1_0_LOG]";
                 end_convo       = "Conv_Q020b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S042=true,T114=true};
                 action			= "[Q020_2_0_ACTN]";
                 log_text		= "[Q020_2_0_LOG]";
                 conversation    = "Conv_Q020c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S042=true,T114=true};
                 action			= "[Q020_3_0_ACTN]";
                 log_text		= "[Q020_3_0_LOG]";
                 conversation    = "Conv_Q020d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B002";
                 monster         = "J053";
                 location        = {S042=true,J053=true};
                 action			= "[Q020_4_0_ACTN]";
                 log_text		= "[Q020_4_0_LOG]";
                 end_text        = "[Q020_4_0_ENDMSG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S042=true,T114=true};
                 action			= "[Q020_5_0_ACTN]";
                 log_text		= "[Q020_5_0_LOG]";
                 end_convo       = "Conv_Q020e";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
                 ACTIONS.hide_location {location="J053", show=false},
   };

   end_actions = {
      [4]={
                 ACTIONS.hide_location {location="J053", show=false},
           };
      [6]={
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.unlock_quest {quest="Q021", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
