--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q021";
   log_text           = "[Q021_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 5;
   start_convo        = "Conv_Q021a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S042=true,T114=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S028=true,T102=true};
                 action			= "[Q021_1_0_ACTN]";
                 log_text		= "[Q021_1_0_LOG]";
                 conversation    = "Conv_Q021b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S028=true,T102=true};
                 action			= "[Q021_2_0_ACTN]";
                 log_text		= "[Q021_2_0_LOG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B011";
                 monster         = "T102";
                 location        = {S028=true,T102=true};
                 action			= "[Q021_3_0_ACTN]";
                 log_text		= "[Q021_3_0_LOG]";
                 end_convo       = "Conv_Q021c";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S042=true,T114=true};
                 action			= "[Q021_4_0_ACTN]";
                 log_text		= "[Q021_4_0_LOG]";
                 conversation    = "Conv_Q021d";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.give_friend {friend="C006", show=true},
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.give_resource {resource="14", amount=14, show=false},
                 ACTIONS.unlock_quest {quest="Q022", show=false},
                 ACTIONS.unlock_quest {quest="Q0GA", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
