--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q022";
   log_text           = "[Q022_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q022a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S042=true,T114=true};

   preconditions = {
      [3]={
      CONDITIONS.min_gold {amount=1000, text="[Q022_2_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S073=true,T120=true};
                 text            = "[Q022_1_0_MSG]";
                 action			= "[Q022_1_0_ACTN]";
                 log_text		= "[Q022_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T120=true};
                 action			= "[Q022_2_0_ACTN]";
                 log_text		= "[Q022_2_0_LOG]";
                 end_text        = "[Q022_2_0_ENDMSG]";
                 end_convo       = "Conv_Q022b";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.unlock_quest {quest="Q023", show=false},
                 ACTIONS.give_experience {amount=60, show=true},
                 ACTIONS.give_gold {amount=-1000, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
