--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q026";
   log_text           = "[Q026_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 2;
   start_convo        = "Conv_Q026a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S072=true,T148=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S013=true,T067=true};
                 action			= "[Q026_1_0_ACTN]";
                 log_text		= "[Q026_1_0_LOG]";
                 end_convo       = "Conv_Q026b";
                 next_state      = 2;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.unlock_quest {quest="Q027", show=false},
                 ACTIONS.give_experience {amount=75, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
