--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q027";
   log_text           = "[Q027_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q027a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S013=true,T067=true};

   preconditions = {
      [3]={
      CONDITIONS.min_gold {amount=2000, text="[Q027_2_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S015=true,T074=true};
                 action			= "[Q027_1_0_ACTN]";
                 log_text		= "[Q027_1_0_LOG]";
                 end_convo       = "Conv_Q027b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S014=true,T070=true};
                 action			= "[Q027_1_1_ACTN]";
                 end_convo       = "Conv_Q027b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T061=true};
                 action			= "[Q027_1_2_ACTN]";
                 end_convo       = "Conv_Q027b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T063=true};
                 action			= "[Q027_1_3_ACTN]";
                 log_text		= "[Q027_1_3_LOG]";
                 end_convo       = "Conv_Q027c";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T063=true};
                 action			= "[Q027_2_0_ACTN]";
                 log_text		= "[Q027_2_0_LOG]";
                 end_text        = "[Q027_2_0_ENDMSG]";
                 end_convo       = "Conv_Q027d";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_experience {amount=75, show=true},
                 ACTIONS.unlock_quest {quest="Q028", show=false},
                 ACTIONS.give_gold {amount=-2000, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
