--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q028";
   log_text           = "[Q028_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q028a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S012=true,T063=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S015=true,T075=true};
                 log_text		= "[Q028_1_0_LOG]";
                 end_convo       = "Conv_Q028b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S015=true,T075=true};
                 action			= "[Q028_2_0_ACTN]";
                 log_text		= "[Q028_2_0_LOG]";
                 end_convo       = "Conv_Q028c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE21";
                 location        = {S015=true,T075=true};
                 action			= "[Q028_3_0_ACTN]";
                 log_text		= "[Q028_3_0_LOG]";
                 end_convo       = "Conv_Q028d";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.unlock_quest {quest="Q029", show=false},
                 ACTIONS.give_experience {amount=75, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
