--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q030";
   log_text           = "[Q030_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 5;
   start_convo        = "Conv_Q030a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S015=true,T075=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S022=true,T001=true};
                 log_text		= "[Q030_1_0_LOG]";
                 end_convo       = "Conv_Q030b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T001=true};
                 action			= "[Q030_2_0_ACTN]";
                 log_text		= "[Q030_2_0_LOG]";
                 end_text        = "[Q030_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S022=true,T000=true};
                 log_text		= "[Q030_3_0_LOG]";
                 end_convo       = "Conv_Q030c";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T000=true};
                 action			= "[Q030_4_0_ACTN]";
                 log_text		= "[Q030_4_0_LOG]";
                 end_text        = "[Q030_4_0_ENDMSG]";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.unlock_quest {quest="Q031", show=false},
                 ACTIONS.give_experience {amount=80, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
