--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q031";
   log_text           = "[Q031_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q031a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S022=true,T000=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S009=true,T060=true};
                 log_text		= "[Q031_1_0_LOG]";
                 end_convo       = "Conv_Q031b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE10";
                 location        = {S009=true,T060=true};
                 action			= "[Q031_2_0_ACTN]";
                 log_text		= "[Q031_2_0_LOG]";
                 conversation    = "Conv_Q031c";
                 end_convo       = "Conv_Q031d";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S022=true,T000=true};
                 log_text		= "[Q031_3_0_LOG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_faction_status {faction="2", amount=-50, show=false},
           };
      [4]={
                 ACTIONS.unlock_quest {quest="Q032", show=false},
                 ACTIONS.give_experience {amount=80, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
