--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q032";
   log_text           = "[Q032_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 6;
   start_convo        = "Conv_Q032a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S022=true,T000=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T000=true};
                 action			= "[Q032_1_0_ACTN]";
                 log_text		= "[Q032_1_0_LOG]";
                 end_convo       = "Conv_Q032b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE02";
                 location        = {S009=true,T059=true};
                 action			= "[Q032_2_0_ACTN]";
                 log_text		= "[Q032_2_0_LOG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE24";
                 location        = {S009=true,T058=true};
                 action			= "[Q032_3_0_ACTN]";
                 log_text		= "[Q032_3_0_LOG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE10";
                 location        = {S009=true,T057=true};
                 action			= "[Q032_4_0_ACTN]";
                 log_text		= "[Q032_4_0_LOG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T000=true};
                 action			= "[Q032_5_0_ACTN]";
                 log_text		= "[Q032_5_0_LOG]";
                 end_convo       = "Conv_Q032c";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_faction_status {faction="4", amount=15, show=false},
           };
      [3]={
                 ACTIONS.give_faction_status {faction="4", amount=15, show=false},
           };
      [4]={
                 ACTIONS.give_faction_status {faction="4", amount=15, show=false},
           };
      [5]={
                 ACTIONS.give_faction_status {faction="4", amount=-50, show=false},
           };
		   
      [6]={
                 ACTIONS.unlock_quest {quest="Q0T5", show=false},
                 ACTIONS.unlock_quest {quest="Q0T4", show=false},
                 ACTIONS.unlock_quest {quest="Q0T0", show=false},
                 ACTIONS.unlock_quest {quest="Q033", show=false},
                 ACTIONS.give_experience {amount=80, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
