--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q033";
   log_text           = "[Q033_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q033a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S022=true,T000=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S026=true,T095=true};
                 log_text		= "[Q033_1_0_LOG]";
                 end_convo       = "Conv_Q033b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE24";
                 location        = {S026=true,T095=true};
                 action			= "[Q033_2_0_ACTN]";
                 log_text		= "[Q033_2_0_LOG]";
                 end_convo       = "Conv_Q033c";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_experience {amount=80, show=true},
                 ACTIONS.give_faction_status {faction="2", amount=-50, show=false},
                 ACTIONS.unlock_quest {quest="Q034", show=false},
                 ACTIONS.show_cutscene {cutscene="CS7"},
          };
   };

   abandon_actions = {
   };

}

return quest
