--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q035";
   log_text           = "[Q035_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 7;
   start_convo        = "Conv_Q035a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S038=true,T194=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S030=true,T166=true};
                 log_text		= "[Q035_1_0_LOG]";
                 end_convo       = "Conv_Q035b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S030=true,T166=true};
                 action			= "[Q035_2_0_ACTN]";
                 log_text		= "[Q035_2_0_LOG]";
                 end_convo       = "Conv_Q035c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S030=true,T166=true};
                 action			= "[Q035_3_0_ACTN]";
                 log_text		= "[Q035_3_0_LOG]";
                 end_convo       = "Conv_Q035d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S030=true,T166=true};
                 action			= "[Q035_4_0_ACTN]";
                 log_text		= "[Q035_4_0_LOG]";
                 end_convo       = "Conv_Q035e";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE17";
                 location        = {S039=true,T212=true};
                 action			= "[Q035_5_0_ACTN]";
                 log_text		= "[Q035_5_0_LOG]";
                 end_text        = "[Q035_5_0_ENDMSG]";
                 next_state      = 6;
              },
           };
      [6]={
              OBJECTIVES.go_to_location {
                 location        = {S030=true,T166=true};
                 action			= "[Q035_6_0_ACTN]";
                 log_text		= "[Q035_6_0_LOG]";
                 end_convo       = "Conv_Q035f";
                 next_state      = 7;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [7]={
                 ACTIONS.unlock_quest {quest="Q0F0", show=false},
                 ACTIONS.unlock_quest {quest="Q036", show=false},
                 ACTIONS.give_experience {amount=80, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
