--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q036";
   log_text           = "[Q036_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q036a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S030=true,T166=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S066=true,T219=true};
                 log_text		= "[Q036_1_0_LOG]";
                 end_convo       = "Conv_Q036b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S066=true,T223=true};
                 action			= "[Q036_2_0_ACTN]";
                 log_text		= "[Q036_2_0_LOG]";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.unlock_quest {quest="Q037", show=false},
                 ACTIONS.give_experience {amount=80, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
