--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q037";
   log_text           = "[Q037_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 5;
   start_convo        = "Conv_Q037a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S066=true,T223=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S066=true,T221=true};
                 log_text		= "[Q037_1_0_LOG]";
                 end_convo       = "Conv_Q037b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE24";
                 location        = {S066=true,T221=true};
                 action			= "[Q037_2_0_ACTN]";
                 log_text		= "[Q037_2_0_LOG]";
                 end_convo       = "Conv_Q037c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE02";
                 location        = {S066=true,T221=true};
                 action			= "[Q037_3_0_ACTN]";
                 log_text		= "[Q037_3_0_LOG]";
                 end_convo       = "Conv_Q037d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE10";
                 location        = {S066=true,T221=true};
                 action			= "[Q037_4_0_ACTN]";
                 log_text		= "[Q037_4_0_LOG]";
                 end_convo       = "Conv_Q037e";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.unlock_quest {quest="Q040", show=false},
                 ACTIONS.give_experience {amount=100, show=true},
                 ACTIONS.show_cutscene {cutscene="CS8"},
          };
   };

   abandon_actions = {
   };

}

return quest
