--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q041";
   log_text           = "[Q041_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 6;
   start_convo        = "Conv_Q041a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S064=true,T237=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S060=true,T259=true};
                 log_text		= "[Q041_1_0_LOG]";
                 end_convo       = "Conv_Q041b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S060=true,T259=true};
                 action			= "[Q041_2_0_ACTN]";
                 log_text		= "[Q041_2_0_LOG]";
                 end_convo       = "Conv_Q041c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S059=true,T263=true};
                 log_text		= "[Q041_3_0_LOG]";
                 end_convo       = "Conv_Q041d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S059=true,T263=true};
                 action			= "[Q041_4_0_ACTN]";
                 log_text		= "[Q041_4_0_LOG]";
                 end_text        = "[Q041_4_0_ENDMSG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S060=true,T259=true};
                 action			= "[Q041_5_0_ACTN]";
                 log_text		= "[Q041_5_0_LOG]";
                 end_convo       = "Conv_Q041e";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [6]={
                 ACTIONS.unlock_quest {quest="Q042", show=false},
                 ACTIONS.give_experience {amount=100, show=true},
                 ACTIONS.unlock_quest {quest="Q0G0", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
