--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q043";
   log_text           = "[Q043_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 6;
   start_convo        = "Conv_Q043a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S054=true,T305=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S055=true,T304=true};
                 action			= "[Q043_1_0_ACTN]";
                 log_text		= "[Q043_1_0_LOG]";
                 end_convo       = "Conv_Q043b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S056=true,T294=true};
                 action			= "[Q043_2_0_ACTN]";
                 log_text		= "[Q043_2_0_LOG]";
                 end_convo       = "Conv_Q043c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S058=true,T290=true};
                 action			= "[Q043_3_0_ACTN]";
                 log_text		= "[Q043_3_0_LOG]";
                 end_convo       = "Conv_Q043d";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S057=true,T301=true};
                 action			= "[Q043_4_0_ACTN]";
                 log_text		= "[Q043_4_0_LOG]";
                 end_convo       = "Conv_Q043e";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location_event {
                 location        = {S054=true,T305=true};
                 log_text		= "[Q043_5_0_LOG]";				 
                 action			= "[Q043_5_0_ACTN]";
                 end_convo       = "Conv_Q043f";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [6]={
                 ACTIONS.give_experience {amount=100, show=true},
                 ACTIONS.unlock_quest {quest="Q044", show=false},
                 ACTIONS.show_cutscene {cutscene="CS9"},
          };
   };

   abandon_actions = {
   };

}

return quest
