--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q044";
   log_text           = "[Q044_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q044a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S054=true,T305=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S051=true,T288=true};
                 action			= "[Q044_1_0_ACTN]";
                 log_text		= "[Q044_1_0_LOG]";
                 end_convo       = "Conv_Q044b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE34";
                 location        = {T288=true};
                 action			= "[Q044_2_0_ACTN]";
                 log_text		= "[Q044_2_0_LOG]";
                 end_text        = "[Q044_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S054=true,T305=true};
                 action			= "[Q044_3_0_ACTN]";
                 log_text		= "[Q044_3_0_LOG]";
                 end_convo       = "Conv_Q044c";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=100, show=true},
                 ACTIONS.unlock_quest {quest="Q045", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
