--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q045";
   log_text           = "[Q045_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 4;
   start_convo        = "Conv_Q045a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S054=true,T305=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S055=true,T304=true};
                 log_text		= "[Q045_1_0_LOG]";
                 end_convo       = "Conv_Q045b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S055=true,T304=true};
                 action			= "[Q045_2_0_ACTN]";
                 log_text		= "[Q045_2_0_LOG]";
                 end_convo       = "Conv_Q045c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S055=true,T304=true};
                 action			= "[Q045_3_0_ACTN]";
                 log_text		= "[Q045_3_0_LOG]";
                 end_convo       = "Conv_Q045d";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=120, show=true},
                 ACTIONS.unlock_quest {quest="Q046", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
