--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q046";
   log_text           = "[Q046_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 5;
   start_convo        = "Conv_Q046a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S055=true,T304=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S054=true,T305=true};
                 log_text		= "[Q046_1_0_LOG]";
                 end_convo       = "Conv_Q046b";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S054=true,T305=true};
                 action			= "[Q046_2_0_ACTN]";
                 log_text		= "[Q046_2_0_LOG]";
                 end_convo       = "Conv_Q046c";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE24";
                 location        = {S054=true,T305=true};
                 action			= "[Q046_3_0_ACTN]";
                 log_text		= "[Q046_3_0_LOG]";
                 end_text        = "[Q046_3_0_ENDMSG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE10";
                 location        = {S054=true,T305=true};
                 action			= "[Q046_4_0_ACTN]";
                 log_text		= "[Q046_4_0_LOG]";
                 end_convo       = "Conv_Q046d";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.unlock_quest {quest="Q047", show=false},
                 ACTIONS.give_experience {amount=120, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
