--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q047";
   log_text           = "[Q047_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 2;
   start_convo        = "Conv_Q047a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S054=true,T305=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S056=true,T294=true};
				 log_text		 = "[Q047_1_0_LOG]";
                 action			 = "[Q047_1_0_ACTN]";
                 end_convo       = "Conv_Q047b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S058=true,T290=true};
                 action			= "[Q047_1_1_ACTN]";
                 end_convo       = "Conv_Q047c";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S055=true,T304=true};
                 action			= "[Q047_1_2_ACTN]";
                 end_convo       = "Conv_Q047b";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S057=true,T301=true};
                 action			= "[Q047_1_3_ACTN]";
                 end_convo       = "Conv_Q047b";
                 next_state      = 1;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_experience {amount=120, show=true},
                 ACTIONS.unlock_quest {quest="Q048", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
