--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q049";
   log_text           = "[Q049_DESC]";
   icon               = "main";
   quest_type         = "main";
   repeatable         = false;
   can_abandon        = false;
   end_state          = 3;
   start_convo        = "Conv_Q049a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S058=true,T290=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S054=true,T305=true};
                 action			= "[Q049_1_0_ACTN]";
                 log_text		= "[Q049_1_0_LOG]";
                 end_convo       = "Conv_Q049b";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S064=true,T237=true};
                 action			= "[Q049_1_1_ACTN]";
                 end_convo       = "Conv_Q049d";
                 next_state      = 3;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S064=true,T237=true};
                 action			= "[Q049_2_0_ACTN]";
                 log_text		= "[Q049_2_0_LOG]";
                 end_convo       = "Conv_Q049c";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
		  		 ACTIONS.remove_friend {friend="C001", show=true},
                 ACTIONS.give_friend {friend="C000", show=true},
           };
      [3]={
                 ACTIONS.give_experience {amount=100, show=true},
                 ACTIONS.give_faction_status {faction="1", amount=100, show=false},
                 ACTIONS.give_gold {amount=1000000, show=true},
                 ACTIONS.show_cutscene {cutscene="CS12"},
                 ACTIONS.remove_friend {friend="C001", show=true},
          };
	  [4]={
				 ACTIONS.give_experience {amount=100, show=true},
				 --ACTIONS.give_gold {amount=1000000, show=true},
				 ACTIONS.give_item {item="PSAGS", show=false},
                 ACTIONS.give_faction_status {faction="1", amount=-100, show=false},
                 ACTIONS.show_cutscene {cutscene="CS11"},
		  };
   };

   abandon_actions = {
   };

}

return quest
