--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0D0";
   log_text           = "[Q0D0_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S012=true,T061=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S023=true,T106=true};
                 log_text		= "[Q0D0_1_0_LOG]";
                 end_text        = "[Q0D0_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE09";
                 location        = {S023=true,T106=true};
                 action			= "[Q0D0_2_0_ACTN]";
                 log_text		= "[Q0D0_2_0_LOG]";
                 end_text        = "[Q0D0_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location_event {
                 location        = {S012=true,T061=true};
                 log_text		= "[Q0D0_3_0_LOG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.give_gold {amount=1000, show=true},
                 ACTIONS.unlock_quest {quest="Q0D1", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
