--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0D1";
   log_text           = "[Q0D1_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 6;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S012=true,T061=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location_event {
                 location        = {S073=true,T315=true};
                 log_text		= "[Q0D1_1_0_LOG]";
                 end_text        = "[Q0D1_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T315=true};
                 action			= "[Q0D1_2_0_ACTN]";
                 log_text		= "[Q0D1_2_0_LOG]";
                 end_text        = "[Q0D1_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE09";
                 location        = {S073=true,T315=true};
                 text            = "[Q0D1_3_0_MSG]";
                 action			= "[Q0D1_3_0_ACTN]";
                 log_text		= "[Q0D1_3_0_LOG]";
                 end_text        = "[Q0D1_3_0_ENDMSG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T315=true};
                 text            = "[Q0D1_4_0_MSG]";
                 action			= "[Q0D1_4_0_ACTN]";
                 log_text		= "[Q0D1_4_0_LOG]";
                 end_text        = "[Q0D1_4_0_ENDMSG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T061=true};
                 action			= "[Q0D1_5_0_ACTN]";
                 log_text		= "[Q0D1_5_0_LOG]";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [6]={
                 ACTIONS.give_experience {amount=30, show=true},
                 ACTIONS.give_gold {amount=1000, show=true},
                 ACTIONS.give_faction_status {faction="8", amount=20, show=false},
                 ACTIONS.unlock_quest {quest="Q0D2", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
