--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0E0";
   log_text           = "[Q0E0_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "[Q0E0_STARTMSG]";
   incomplete_message = "";
   start_locations = {S010=true,T054=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q0E0_1_0_ACTN]";
                 log_text		= "[Q0E0_1_0_LOG]";
                 end_convo       = "Conv_Q0E0a";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE26";
                 location        = {S072=true,T150=true};
                 action			= "[Q0E0_2_0_ACTN]";
                 log_text		= "[Q0E0_2_0_LOG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q0E0_3_0_ACTN]";
                 log_text		= "[Q0E0_3_0_LOG]";
                 end_convo       = "Conv_Q0E0b";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.unlock_quest {quest="Q0E1", show=false},
                 ACTIONS.give_experience {amount=25, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
