--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0E1";
   log_text           = "[Q0E1_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 6;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "[Q0E1_STARTMSG]";
   incomplete_message = "";
   start_locations = {S075=true,T140=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE36";
                 location        = {S075=true,T140=true};
                 action			= "[Q0E1_1_0_ACTN]";
                 log_text		= "[Q0E1_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q0E1_2_0_ACTN]";
                 log_text		= "[Q0E1_2_0_LOG]";
                 end_text        = "[Q0E1_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE20";
                 location        = {S075=true,T140=true};
                 action			= "[Q0E1_3_0_ACTN]";
                 log_text		= "[Q0E1_3_0_LOG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q0E1_4_0_ACTN]";
                 log_text		= "[Q0E1_4_0_LOG]";
                 end_text        = "[Q0E1_4_0_ENDMSG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T054=true};
                 action			= "[Q0E1_5_0_ACTN]";
                 log_text		= "[Q0E1_5_0_LOG]";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.give_gold {amount=5000, show=true},
           };
      [6]={
                 ACTIONS.give_faction_status {faction="6", amount=25, show=false},
                 ACTIONS.give_gold {amount=5000, show=true},
                 ACTIONS.give_experience {amount=50, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
