--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0E2";
   log_text           = "[Q0E2_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S010=true,T054=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T061=true};
                 text            = "[Q0E2_1_0_MSG]";
                 action			= "[Q0E2_1_0_ACTN]";
                 log_text		= "[Q0E2_1_0_LOG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE13";
                 location        = {S012=true,T061=true};
                 action			= "[Q0E2_2_0_ACTN]";
                 log_text		= "[Q0E2_2_0_LOG]";
                 end_text        = "[Q0E2_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T054=true};
                 action			= "[Q0E2_3_0_ACTN]";
                 log_text		= "[Q0E2_3_0_LOG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=10, show=true},
                 ACTIONS.give_gold {amount=1000, show=true},
                 ACTIONS.give_faction_status {faction="6", amount=15, show=false},
                 ACTIONS.give_faction_status {faction="8", amount=-20, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
