--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0EA";
   log_text           = "[Q0EA_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 2;
   start_convo        = "Conv_Q0EAa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S030=true,T166=true};

   preconditions = {
      [2]={
      CONDITIONS.min_gold {amount=2500, text="[Q0EA_2_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S073=true,T120=true};
                 action			= "[Q0EA_1_0_ACTN]";
                 log_text		= "[Q0EA_1_0_LOG]";
                 end_text        = "[Q0EA_1_0_ENDMSG]";
                 end_convo       = "Conv_Q0EAb";
                 next_state      = 2;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_gold {amount=-2500, show=false},
                 ACTIONS.give_experience {amount=50, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
