--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0F3";
   log_text           = "[Q0F3_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 3;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S030=true,T166=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE38";
                 location        = {S044=true,T232=true};
                 action			= "[Q0F3_1_0_ACTN]";
                 log_text		= "[Q0F3_1_0_LOG]";
                 end_text        = "[Q0F3_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S030=true,T166=true};
                 action			= "[Q0F3_2_0_ACTN]";
                 log_text		= "[Q0F3_2_0_LOG]";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_gold {amount=2000, show=true},
                 ACTIONS.give_faction_status {faction="3", amount=10, show=false},
                 ACTIONS.give_experience {amount=40, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
