--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0G0";
   log_text           = "[Q0G0_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 2;
   start_convo        = "Conv_Q0G0a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S060=true,T259=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S033=true,T216=true};
                 action			= "[Q0G0_1_0_ACTN]";
                 log_text		= "[Q0G0_1_0_LOG]";
                 next_state      = 2;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.unlock_quest {quest="Q0G1", show=false},
                 ACTIONS.give_gold {amount=1000, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
