--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0G1";
   log_text           = "[Q0G1_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 2;
   start_convo        = "Conv_Q0G1a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S060=true,T259=true};

   preconditions = {
      [2]={
      CONDITIONS.min_gold {amount=5500, text="[Q0G1_2_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S047=true,T267=true};
                 action			= "[Q0G1_1_0_ACTN]";
                 log_text		= "[Q0G1_1_0_LOG]";
                 next_state      = 2;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_gold {amount=-5500, show=false},
                 ACTIONS.give_resource {resource="10", amount=50, show=true},
                 ACTIONS.unlock_quest {quest="Q0G2", show=false},
                 ACTIONS.give_experience {amount=10, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
