--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0GA";
   log_text           = "[Q0GA_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 6;
   start_convo        = "Conv_Q0GAa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S066=true,T221=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S066=true,T221=true};
                 action			= "[Q0GA_1_0_ACTN]";
                 log_text		= "[Q0GA_1_0_LOG]";
                 end_convo       = "Conv_Q0GAb";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE10";
                 location        = {S066=true,T222=true};
                 action			= "[Q0GA_2_0_ACTN]";
                 log_text		= "[Q0GA_2_0_LOG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE01";
                 location        = {S066=true,T220=true};
                 action			= "[Q0GA_3_0_ACTN]";
                 log_text		= "[Q0GA_3_0_LOG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE24";
                 location        = {S066=true,T223=true};
                 action			= "[Q0GA_4_0_ACTN]";
                 log_text		= "[Q0GA_4_0_LOG]";
                 next_state      = 5;
              },
           };
      [5]={
              OBJECTIVES.go_to_location {
                 location        = {S066=true,T221=true};
                 action			= "[Q0GA_5_0_ACTN]";
                 log_text		= "[Q0GA_5_0_LOG]";
                 end_convo       = "Conv_Q0GAc";
                 next_state      = 6;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [6]={
                 ACTIONS.unlock_quest {quest="Q0GB", show=false},
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.give_faction_status {faction="10", amount=10, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
