--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0J0";
   log_text           = "[Q0J0_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S075=true,T140=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S072=true,T148=true};
                 action			= "[Q0J0_1_0_ACTN]";
                 log_text		= "[Q0J0_1_0_LOG]";
                 end_text        = "[Q0J0_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE09";
                 location        = {S072=true,T148=true};
                 action			= "[Q0J0_2_0_ACTN]";
                 log_text		= "[Q0J0_2_0_LOG]";
                 end_text        = "[Q0J0_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S075=true,T140=true};
                 action			= "[Q0J0_3_0_ACTN]";
                 log_text		= "[Q0J0_3_0_LOG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_faction_status {faction="9", amount=5, show=false},
                 ACTIONS.give_faction_status {faction="7", amount=-10, show=false},
                 ACTIONS.unlock_quest {quest="Q0J1", show=false},
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.give_gold {amount=2000, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
