--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0LA";
   log_text           = "[Q0LA_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 3;
   start_convo        = "Conv_Q0LAa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S010=true,T054=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T054=true};
                 action			= "[Q0LA_1_0_ACTN]";
                 log_text		= "[Q0LA_1_0_LOG]";
                 end_convo       = "Conv_Q0LAb";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T000=true};
                 action			= "[Q0LA_2_0_ACTN]";
                 log_text		= "[Q0LA_2_0_LOG]";
                 end_convo       = "Conv_Q0LAc";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.unlock_quest {quest="Q0LB", show=false},
                 ACTIONS.give_experience {amount=50, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
