--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0LB";
   log_text           = "[Q0LB_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 3;
   start_convo        = "Conv_Q0LBa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S039=true,T213=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE16";
                 location        = {S037=true,T197=true};
                 action			= "[Q0LB_1_0_ACTN]";
                 log_text		= "[Q0LB_1_0_LOG]";
                 end_convo       = "Conv_Q0LBb";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S038=true,T192=true};
                 action			= "[Q0LB_2_0_ACTN]";
                 log_text		= "[Q0LB_2_0_LOG]";
                 end_convo       = "Conv_Q0LBc";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.unlock_quest {quest="Q0LC", show=false},
                 ACTIONS.give_experience {amount=50, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
