--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0LE";
   log_text           = "[Q0LE_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 5;
   start_convo        = "Conv_Q0LEa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S059=true,T263=true};

   preconditions = {
      [2]={
      CONDITIONS.min_gold {amount=1500, text="[Q0LE_2_0_PRE]"},
           };
      [4]={
      CONDITIONS.min_gold {amount=1500, text="[Q0LE_4_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T061=true};
                 action			= "[Q0LE_1_0_ACTN]";
                 log_text		= "[Q0LE_1_0_LOG]";
                 end_text        = "[Q0LE_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S059=true,T263=true};
                 action			= "[Q0LE_2_0_ACTN]";
                 log_text		= "[Q0LE_2_0_LOG]";
                 end_convo       = "Conv_Q0LEb";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S012=true,T061=true};
                 action			= "[Q0LE_3_0_ACTN]";
                 log_text		= "[Q0LE_3_0_LOG]";
                 end_text        = "[Q0LE_3_0_ENDMSG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S059=true,T263=true};
                 action			= "[Q0LE_4_0_ACTN]";
                 log_text		= "[Q0LE_4_0_LOG]";
                 end_convo       = "Conv_Q0LEc";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [2]={
                 ACTIONS.give_gold {amount=-1500, show=false},
           };
      [4]={
                 ACTIONS.give_gold {amount=-1500, show=false},
           };
      [5]={
                 ACTIONS.unlock_quest {quest="Q0LF", show=false},
                 ACTIONS.give_experience {amount=50, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
