--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0LG";
   log_text           = "[Q0LG_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "[Q0LG_STARTMSG]";
   incomplete_message = "";
   start_locations = {S059=true,T263=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S059=true,T263=true};
                 action			= "[Q0LG_1_0_ACTN]";
                 log_text		= "[Q0LG_1_0_LOG]";
                 end_text        = "[Q0LG_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE40";
                 location        = {S059=true,T263=true};
                 action			= "[Q0LG_2_0_ACTN]";
                 log_text		= "[Q0LG_2_0_LOG]";
                 end_text        = "[Q0LG_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE42";
                 location        = {S059=true,T263=true};
                 action			= "[Q0LG_3_0_ACTN]";
                 log_text		= "[Q0LG_3_0_LOG]";
                 end_convo       = "Conv_Q0LGa";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=200, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
