--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0P2";
   log_text           = "[Q0P2_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S064=true,T237=true};

   preconditions = {
      [3]={
      CONDITIONS.min_gold {amount=2000, text="[Q0P2_2_0_PRE]"},
          };
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T052=true};
                 action			= "[Q0P2_1_0_ACTN]";
                 log_text		= "[Q0P2_1_0_LOG]";
                 end_convo       = "Conv_Q0P2a";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S010=true,T054=true};
                 action			= "[Q0P2_2_0_ACTN]";
                 log_text		= "[Q0P2_2_0_LOG]";
                 end_text        = "[Q0P2_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S064=true,T237=true};
                 action			= "[Q0P2_3_0_ACTN]";
                 log_text		= "[Q0P2_3_0_LOG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_gold {amount=-2000, show=false},
           };
      [4]={
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.give_gold {amount=5000, show=true},
                 ACTIONS.give_faction_status {faction="12", amount=25, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
