--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0Q1";
   log_text           = "[Q0Q1_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 3;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S042=true,T114=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S011=true,T047=true};
                 action			= "[Q0Q1_1_0_ACTN]";
                 log_text		= "[Q0Q1_1_0_LOG]";
                 end_text        = "[Q0Q1_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.go_to_location {
                 location        = {S042=true,T114=true};
                 action			= "[Q0Q1_2_0_ACTN]";
                 log_text		= "[Q0Q1_2_0_LOG]";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.unlock_quest {quest="Q0Q2", show=false},
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.give_gold {amount=1000, show=true},
                 ACTIONS.give_faction_status {faction="11", amount=10, show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
