--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0SA";
   log_text           = "[Q0SA_DESC]";
   icon               = "character";
   quest_type         = "character";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 3;
   start_convo        = "Conv_Q0SAa";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S005=true,T022=true};

   preconditions = {
   [1]={
      CONDITIONS.has_friend {friend="C002"},
          };
   };
   
   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T026=true};
                 log_text		= "[Q0SA_1_0_LOG]";				 
                 action			= "[Q0SA_1_0_ACTN]";
                 end_text        = "[Q0SA_1_0_ENDMSG]";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T028=true};
                 action			= "[Q0SA_1_1_ACTN]";
                 end_text        = "[Q0SA_1_1_ENDMSG]";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T027=true};
                 action			= "[Q0SA_1_2_ACTN]";
                 end_text        = "[Q0SA_1_2_ENDMSG]";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T029=true};
                 action			= "[Q0SA_1_3_ACTN]";
                 log_text		= "[Q0SA_1_3_LOG]";
                 end_convo       = "Conv_Q0SAb";
                 next_state      = 2;
              },
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T032=true};
                 action			= "[Q0SA_1_4_ACTN]";
                 end_convo       = "Conv_Q0SAd";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T030=true};
                 action			= "[Q0SA_1_5_ACTN]";
                 end_convo       = "Conv_Q0SAd";
                 next_state      = 1;
              },
              OBJECTIVES.go_to_location {
                 location        = {S008=true,T031=true};
                 action			= "[Q0SA_1_6_ACTN]";
                 end_convo       = "Conv_Q0SAd";
                 next_state      = 1;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S008=true,T029=true};
                 action			= "[Q0SA_2_0_ACTN]";
                 log_text		= "[Q0SA_2_0_LOG]";
                 end_convo       = "Conv_Q0SAc";
                 next_state      = 3;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [3]={
                 ACTIONS.give_experience {amount=25, show=true},
                 ACTIONS.unlock_quest {quest="Q0SB", show=false},
          };
   };

   abandon_actions = {
   };

}

return quest
