--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0T1";
   log_text           = "[Q0T1_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 4;
   start_convo        = "";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S022=true,T000=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE39";
                 location        = {S077=true,T157=true};
                 text            = "[Q0T1_1_0_MSG]";
                 action			= "[Q0T1_1_0_ACTN]";
                 log_text		= "[Q0T1_1_0_LOG]";
                 end_text        = "[Q0T1_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE26";
                 location        = {S077=true,T157=true};
                 text            = "[Q0T1_2_0_MSG]";
                 action			= "[Q0T1_2_0_ACTN]";
                 log_text		= "[Q0T1_2_0_LOG]";
                 end_text        = "[Q0T1_2_0_ENDMSG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T001=true};
                 action			= "[Q0T1_3_0_ACTN]";
                 log_text		= "[Q0T1_3_0_LOG]";
                 next_state      = 4;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [4]={
                 ACTIONS.give_experience {amount=35, show=true},
                 ACTIONS.unlock_quest {quest="Q0T2", show=false},
                 ACTIONS.give_gold {amount=500, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
