--
-- This file is autogenerated by QuestXml2Lua
--
require "quests/Quest" 


local quest = Quest {

   id                 = "Q0T3";
   log_text           = "[Q0T3_DESC]";
   icon               = "side";
   quest_type         = "side";
   repeatable         = false;
   can_abandon        = true;
   end_state          = 5;
   start_convo        = "Conv_Q0T3a";
   incomplete_convo   = "";
   level_min          = 1;
   level_max          = 999;
   start_message      = "";
   incomplete_message = "";
   start_locations = {S022=true,T000=true};

   preconditions = {
   };

   objectives = {
      [1]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T001=true};
                 action			= "[Q0T3_1_0_ACTN]";
                 log_text		= "[Q0T3_1_0_LOG]";
                 end_text        = "[Q0T3_1_0_ENDMSG]";
                 next_state      = 2;
              },
           };
      [2]={
              OBJECTIVES.kill_monster {
                 battleground    = "B001";
                 monster         = "HE26";
                 location        = {S038=true,T192=true};
                 text            = "[Q0T3_2_0_MSG]";
                 action			= "[Q0T3_2_0_ACTN]";
                 log_text		= "[Q0T3_2_0_LOG]";
                 next_state      = 3;
              },
           };
      [3]={
              OBJECTIVES.go_to_location {
                 location        = {S038=true,T192=true};
                 action			= "[Q0T3_3_0_ACTN]";
                 log_text		= "[Q0T3_3_0_LOG]";
                 next_state      = 4;
              },
           };
      [4]={
              OBJECTIVES.go_to_location {
                 location        = {S022=true,T000=true};
                 action			= "[Q0T3_4_0_ACTN]";
                 log_text		= "[Q0T3_4_0_LOG]";
                 next_state      = 5;
              },
          };
   };

   start_actions = {
   };

   end_actions = {
      [5]={
                 ACTIONS.give_experience {amount=50, show=true},
                 ACTIONS.give_gold {amount=10000, show=true},
          };
   };

   abandon_actions = {
   };

}

return quest
