-----------------------------------------
--
--  Gate: S000 <-> S001
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 339;
          sat_ypos = 471;
          keys     = 20;
          time     = 110;
       }
