-----------------------------------------
--
--  Gate: S000 <-> S002
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1018;
          sat_ypos = 507;
          keys     = 12;
          time     = 120;
       }
