-----------------------------------------
--
--  Gate: S000 <-> S005
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 861;
          sat_ypos = 267;
          keys     = 12;
          time     = 120;
       }
