-----------------------------------------
--
--  Gate: S002 <-> S003
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1093;
          sat_ypos = 465;
          keys     = 12;
          time     = 95;
       }
