-----------------------------------------
--
--  Gate: S005 <-> S006
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 310;
          sat_ypos = 229;
          keys     = 12;
          time     = 70;
       }
