-----------------------------------------
--
--  Gate: S005 <-> S007
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1032;
          sat_ypos = 297;
          keys     = 16;
          time     = 115;
       }
