-----------------------------------------
--
--  Gate: S004 <-> S005
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 385;
          sat_ypos = 226;
          keys     = 12;
          time     = 95;
       }
