-----------------------------------------
--
--  Gate: S021 <-> S022
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 845;
          sat_ypos = 274;
          keys     = 24;
          time     = 180;
       }
