-----------------------------------------
--
--  Gate: S022 <-> S024
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 250;
          sat_ypos = 377;
          keys     = 24;
          time     = 100;
       }
