-----------------------------------------
--
--  Gate: S022 <-> S025
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 351;
          sat_ypos = 224;
          keys     = 24;
          time     = 130;
       }
