-----------------------------------------
--
--  Gate: S022 <-> S026
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 611;
          sat_ypos = 182;
          keys     = 24;
          time     = 130;
       }
