-----------------------------------------
--
--  Gate: S022 <-> S027
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 940;
          sat_ypos = 269;
          keys     = 24;
          time     = 155;
       }
