-----------------------------------------
--
--  Gate: S022 <-> S028
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1087;
          sat_ypos = 427;
          keys     = 24;
          time     = 130;
       }
