-----------------------------------------
--
--  Gate: S022 <-> S023
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 845;
          sat_ypos = 511;
          keys     = 16;
          time     = 90;
       }
