-----------------------------------------
--
--  Gate: S003 <-> S004
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 532;
          sat_ypos = 205;
          keys     = 12;
          time     = 95;
       }
