-----------------------------------------
--
--  Gate: S007 <-> S008
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 353;
          sat_ypos = 226;
          keys     = 12;
          time     = 55;
       }
