-----------------------------------------
--
--  Gate: S007 <-> S009
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1049;
          sat_ypos = 304;
          keys     = 16;
          time     = 115;
       }
