-----------------------------------------
--
--  Gate: S009 <-> S010
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1036;
          sat_ypos = 507;
          keys     = 16;
          time     = 115;
       }
