-----------------------------------------
--
--  Gate: S009 <-> S021
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1019;
          sat_ypos = 291;
          keys     = 8;
          time     = 75;
       }
