-----------------------------------------
--
--  Gate: S010 <-> S011
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 609;
          sat_ypos = 573;
          keys     = 12;
          time     = 95;
       }
