-----------------------------------------
--
--  Gate: S010 <-> S023
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1051;
          sat_ypos = 352;
          keys     = 16;
          time     = 90;
       }
