-----------------------------------------
--
--  Gate: S011 <-> S012
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1058;
          sat_ypos = 372;
          keys     = 16;
          time     = 115;
       }
