-----------------------------------------
--
--  Gate: S003 <-> S011
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 865;
          sat_ypos = 279;
          keys     = 12;
          time     = 95;
       }
