-----------------------------------------
--
--  Gate: S012 <-> S013
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1049;
          sat_ypos = 544;
          keys     = 20;
          time     = 135;
       }
