-----------------------------------------
--
--  Gate: S012 <-> S016
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 966;
          sat_ypos = 296;
          keys     = 16;
          time     = 115;
       }
