-----------------------------------------
--
--  Gate: S013 <-> S020
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1088;
          sat_ypos = 265;
          keys     = 20;
          time     = 135;
       }
