-----------------------------------------
--
--  Gate: S013 <-> S014
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1077;
          sat_ypos = 502;
          keys     = 20;
          time     = 135;
       }
