-----------------------------------------
--
--  Gate: S014 <-> S015
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1126;
          sat_ypos = 245;
          keys     = 20;
          time     = 110;
       }
