-----------------------------------------
--
--  Gate: S018 <-> S020
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 265;
          sat_ypos = 502;
          keys     = 20;
          time     = 110;
       }
