-----------------------------------------
--
--  Gate: S018 <-> S019
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 988;
          sat_ypos = 496;
          keys     = 20;
          time     = 95;
       }
