-----------------------------------------
--
--  Gate: S017 <-> S018
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1049;
          sat_ypos = 523;
          keys     = 16;
          time     = 90;
       }
