-----------------------------------------
--
--  Gate: S018 <-> S072
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 914;
          sat_ypos = 290;
          keys     = 24;
          time     = 155;
       }
