-----------------------------------------
--
--  Gate: S016 <-> S017
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1027;
          sat_ypos = 286;
          keys     = 12;
          time     = 70;
       }
