-----------------------------------------
--
--  Gate: S017 <-> S073
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 391;
          sat_ypos = 242;
          keys     = 16;
          time     = 115;
       }
