-----------------------------------------
--
--  Gate: S016 <-> S023
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 438;
          sat_ypos = 255;
          keys     = 16;
          time     = 90;
       }
