-----------------------------------------
--
--  Gate: S023 <-> S073
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1004;
          sat_ypos = 299;
          keys     = 16;
          time     = 90;
       }
