-----------------------------------------
--
--  Gate: S073 <-> S074
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 768;
          sat_ypos = 161;
          keys     = 20;
          time     = 110;
       }
