-----------------------------------------
--
--  Gate: S060 <-> S062
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 420;
          sat_ypos = 541;
          keys     = 16;
          time     = 75;
       }
