-----------------------------------------
--
--  Gate: S060 <-> S063
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 966;
          sat_ypos = 492;
          keys     = 12;
          time     = 55;
       }
