-----------------------------------------
--
--  Gate: S060 <-> S061
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1063;
          sat_ypos = 296;
          keys     = 20;
          time     = 95;
       }
