-----------------------------------------
--
--  Gate: S053 <-> S060
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 691;
          sat_ypos = 483;
          keys     = 20;
          time     = 95;
       }
