-----------------------------------------
--
--  Gate: S053 <-> S059
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 288;
          sat_ypos = 299;
          keys     = 12;
          time     = 55;
       }
