-----------------------------------------
--
--  Gate: S053 <-> S054
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 985;
          sat_ypos = 363;
          keys     = 24;
          time     = 115;
       }
