-----------------------------------------
--
--  Gate: S052 <-> S053
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 730;
          sat_ypos = 551;
          keys     = 20;
          time     = 95;
       }
