-----------------------------------------
--
--  Gate: S025 <-> S029
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 277;
          sat_ypos = 397;
          keys     = 16;
          time     = 115;
       }
