-----------------------------------------
--
--  Gate: S025 <-> S030
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 556;
          sat_ypos = 206;
          keys     = 12;
          time     = 70;
       }
