-----------------------------------------
--
--  Gate: S074 <-> S075
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1037;
          sat_ypos = 325;
          keys     = 20;
          time     = 135;
       }
