-----------------------------------------
--
--  Gate: S075 <-> S076
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 913;
          sat_ypos = 501;
          keys     = 20;
          time     = 135;
       }
