-----------------------------------------
--
--  Gate: S075 <-> S077
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 798;
          sat_ypos = 163;
          keys     = 20;
          time     = 135;
       }
