-----------------------------------------
--
--  Gate: S030 <-> S031
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 513;
          sat_ypos = 219;
          keys     = 12;
          time     = 95;
       }
