-----------------------------------------
--
--  Gate: S030 <-> S033
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1028;
          sat_ypos = 303;
          keys     = 16;
          time     = 115;
       }
