-----------------------------------------
--
--  Gate: S071 <-> S072
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 450;
          sat_ypos = 499;
          keys     = 20;
          time     = 110;
       }
