-----------------------------------------
--
--  Gate: S072 <-> S076
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 281;
          sat_ypos = 298;
          keys     = 16;
          time     = 90;
       }
