-----------------------------------------
--
--  Gate: S028 <-> S042
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 873;
          sat_ypos = 267;
          keys     = 20;
          time     = 135;
       }
