-----------------------------------------
--
--  Gate: S027 <-> S042
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 972;
          sat_ypos = 502;
          keys     = 16;
          time     = 90;
       }
