-----------------------------------------
--
--  Gate: S027 <-> S041
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 841;
          sat_ypos = 213;
          keys     = 16;
          time     = 90;
       }
