-----------------------------------------
--
--  Gate: S026 <-> S033
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 427;
          sat_ypos = 219;
          keys     = 20;
          time     = 110;
       }
