-----------------------------------------
--
--  Gate: S033 <-> S034
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 401;
          sat_ypos = 215;
          keys     = 12;
          time     = 70;
       }
