-----------------------------------------
--
--  Gate: S033 <-> S039
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1073;
          sat_ypos = 306;
          keys     = 12;
          time     = 70;
       }
