-----------------------------------------
--
--  Gate: S070 <-> S071
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 965;
          sat_ypos = 500;
          keys     = 20;
          time     = 110;
       }
