-----------------------------------------
--
--  Gate: S069 <-> S070
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 628;
          sat_ypos = 572;
          keys     = 20;
          time     = 110;
       }
