-----------------------------------------
--
--  Gate: S070 <-> S077
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 271;
          sat_ypos = 295;
          keys     = 16;
          time     = 90;
       }
