-----------------------------------------
--
--  Gate: S077 <-> S078
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 304;
          sat_ypos = 243;
          keys     = 16;
          time     = 90;
       }
