-----------------------------------------
--
--  Gate: S042 <-> S078
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 985;
          sat_ypos = 320;
          keys     = 20;
          time     = 135;
       }
