-----------------------------------------
--
--  Gate: S040 <-> S041
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1107;
          sat_ypos = 503;
          keys     = 16;
          time     = 115;
       }
