-----------------------------------------
--
--  Gate: S041 <-> S065
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 840;
          sat_ypos = 238;
          keys     = 20;
          time     = 95;
       }
