-----------------------------------------
--
--  Gate: S041 <-> S064
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1061;
          sat_ypos = 366;
          keys     = 20;
          time     = 95;
       }
