-----------------------------------------
--
--  Gate: S062 <-> S064
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 961;
          sat_ypos = 503;
          keys     = 16;
          time     = 75;
       }
