-----------------------------------------
--
--  Gate: S064 <-> S068
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 988;
          sat_ypos = 397;
          keys     = 24;
          time     = 180;
       }
