-----------------------------------------
--
--  Gate: S067 <-> S068
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 569;
          sat_ypos = 529;
          keys     = 20;
          time     = 95;
       }
