-----------------------------------------
--
--  Gate: S068 <-> S069
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 924;
          sat_ypos = 556;
          keys     = 8;
          time     = 50;
       }
