-----------------------------------------
--
--  Gate: S054 <-> S061
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 509;
          sat_ypos = 598;
          keys     = 24;
          time     = 115;
       }
