-----------------------------------------
--
--  Gate: S054 <-> S055
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 749;
          sat_ypos = 252;
          keys     = 24;
          time     = 100;
       }
