-----------------------------------------
--
--  Gate: S055 <-> S056
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1021;
          sat_ypos = 320;
          keys     = 24;
          time     = 100;
       }
