-----------------------------------------
--
--  Gate: S056 <-> S057
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 907;
          sat_ypos = 497;
          keys     = 24;
          time     = 100;
       }
