-----------------------------------------
--
--  Gate: S056 <-> S058
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1025;
          sat_ypos = 313;
          keys     = 24;
          time     = 100;
       }
