-----------------------------------------
--
--  Gate: S044 <-> S045
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 723;
          sat_ypos = 208;
          keys     = 20;
          time     = 135;
       }
