-----------------------------------------
--
--  Gate: S045 <-> S046
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 311;
          sat_ypos = 327;
          keys     = 24;
          time     = 115;
       }
