-----------------------------------------
--
--  Gate: S045 <-> S050
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1049;
          sat_ypos = 319;
          keys     = 20;
          time     = 110;
       }
