-----------------------------------------
--
--  Gate: S043 <-> S044
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 997;
          sat_ypos = 319;
          keys     = 20;
          time     = 135;
       }
