-----------------------------------------
--
--  Gate: S065 <-> S066
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 318;
          sat_ypos = 287;
          keys     = 20;
          time     = 95;
       }
