-----------------------------------------
--
--  Gate: S050 <-> S051
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1073;
          sat_ypos = 312;
          keys     = 20;
          time     = 135;
       }
