-----------------------------------------
--
--  Gate: S051 <-> S052
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1079;
          sat_ypos = 516;
          keys     = 24;
          time     = 115;
       }
