-----------------------------------------
--
--  Gate: S046 <-> S048
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 716;
          sat_ypos = 137;
          keys     = 20;
          time     = 95;
       }
