-----------------------------------------
--
--  Gate: S046 <-> S047
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 268;
          sat_ypos = 377;
          keys     = 16;
          time     = 75;
       }
