-----------------------------------------
--
--  Gate: S048 <-> S049
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 293;
          sat_ypos = 222;
          keys     = 16;
          time     = 75;
       }
