-----------------------------------------
--
--  Gate: S037 <-> S038
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 610;
          sat_ypos = 553;
          keys     = 12;
          time     = 95;
       }
