-----------------------------------------
--
--  Gate: S037 <-> S043
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 843;
          sat_ypos = 237;
          keys     = 16;
          time     = 90;
       }
