-----------------------------------------
--
--  Gate: S036 <-> S037
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1044;
          sat_ypos = 556;
          keys     = 20;
          time     = 110;
       }
