-----------------------------------------
--
--  Gate: S038 <-> S039
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 792;
          sat_ypos = 507;
          keys     = 20;
          time     = 95;
       }
