-----------------------------------------
--
--  Gate: S039 <-> S040
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1092;
          sat_ypos = 394;
          keys     = 12;
          time     = 70;
       }
