-----------------------------------------
--
--  Gate: S032 <-> S034
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1041;
          sat_ypos = 308;
          keys     = 20;
          time     = 110;
       }
