-----------------------------------------
--
--  Gate: S034 <-> S035
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 554;
          sat_ypos = 173;
          keys     = 20;
          time     = 110;
       }
