-----------------------------------------
--
--  Gate: S031 <-> S032
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 799;
          sat_ypos = 193;
          keys     = 16;
          time     = 90;
       }
