-----------------------------------------
--
--  Gate: S035 <-> S036
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {  sat_xpos = 1064;
          sat_ypos = 307;
          keys     = 20;
          time     = 110;
       }
