-----------------------------------------
--
--  T002: Erebus II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 630;
   sat_ypos = 455;
}
