-----------------------------------------
--
--  T003: Erebus Sigma Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 582;
   sat_ypos = 292;
}
