-----------------------------------------
--
--  T004: E3CF36J
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 314;
   sat_ypos = 121;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCAL"]=4,["GCTX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=15},
              [2]={cargo=_G.CARGO_ALLOYS, min=10},
              [3]={cargo=_G.CARGO_TEXTILES, min=3},
             };
}
