-----------------------------------------
--
--  T005: Erebus Shipyard
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 809;
   sat_ypos = 525;
   shop_list = import("Satellites/T005_shop");
}
