-----------------------------------------
--
--  T006: E5GH56P
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 517;
   sat_ypos = 99;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCLX"]=4,["GCTX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=18},
              [2]={cargo=_G.CARGO_LUXURIES, min=12},
              [3]={cargo=_G.CARGO_TEXTILES, min=4},
             };
}
