-----------------------------------------
--
--  T007: P4IU987
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 281;
   sat_ypos = 336;
   gemList = {["GBLX"]=9,["GCAL"]=9,["GCMN"]=6,["GCGM"]=3};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=30},
              [2]={cargo=_G.CARGO_MINERALS, min=20},
              [3]={cargo=_G.CARGO_GEMS, min=8},
             };
}
