-----------------------------------------
--
--  T008: Quaris IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 389;
   sat_ypos = 167;
}
