-----------------------------------------
--
--  T009: TX967R
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 563;
   sat_ypos = 474;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCMN"]=4,["GCON"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=25},
              [2]={cargo=_G.CARGO_MINERALS, min=20},
              [3]={cargo=_G.CARGO_CONTRABAND, min=8},
             };
}
