-----------------------------------------
--
--  T010: Quaris II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 123;
   sat_ypos = 451;
}
