-----------------------------------------
--
--  T011: QP Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 657;
   sat_ypos = 246;
}
