-----------------------------------------
--
--  T013: Gemini Engines
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 150;
   sat_ypos = 501;
   shop_list = import("Satellites/T013_shop");
}
