-----------------------------------------
--
--  T014: XK786T
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1024;
   sat_ypos = 152;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCFD"]=4,["GCMN"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=18},
              [2]={cargo=_G.CARGO_FOOD, min=12},
              [3]={cargo=_G.CARGO_MINERALS, min=4},
             };
}
