-----------------------------------------
--
--  T015: Talosian Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 622;
   sat_ypos = 168;
}
