-----------------------------------------
--
--  T016: XG124P
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 624;
   sat_ypos = 496;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCON"]=4,["GCGD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=20},
              [2]={cargo=_G.CARGO_CONTRABAND, min=16},
              [3]={cargo=_G.CARGO_GOLD, min=6},
             };
}
