-----------------------------------------
--
--  T017: Caelum II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 415;
   sat_ypos = 329;
}
