-----------------------------------------
--
--  T018: Caelum V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 973;
   sat_ypos = 245;
}
