-----------------------------------------
--
--  T019: SR317D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 182;
   sat_ypos = 199;
   gemList = {["GBLX"]=9,["GCTX"]=9,["GCMN"]=6,["GCMD"]=3};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=40},
              [2]={cargo=_G.CARGO_MINERALS, min=27},
              [3]={cargo=_G.CARGO_MEDICINE, min=13},
             };
}
