-----------------------------------------
--
--  T020: PH374V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 613;
   sat_ypos = 504;
   gemList = {["GBLX"]=9,["GCON"]=9,["GCMN"]=6,["GCTX"]=3};
   cargo   = {[1]={cargo=_G.CARGO_CONTRABAND, min=35},
              [2]={cargo=_G.CARGO_MINERALS, min=22},
              [3]={cargo=_G.CARGO_TEXTILES, min=11},
             };
}
