-----------------------------------------
--
--  T021: Caelum Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 715;
   sat_ypos = 320;
}
