-----------------------------------------
--
--  T023: Ceti CPUs
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 763;
   sat_ypos = 186;
   shop_list = import("Satellites/T023_shop");
}
