-----------------------------------------
--
--  T024: PS213M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 152;
   sat_ypos = 420;
   gemList = {["GBLX"]=9,["GCAL"]=9,["GCMN"]=6,["GCTK"]=3};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=40},
              [2]={cargo=_G.CARGO_MINERALS, min=27},
              [3]={cargo=_G.CARGO_TECH, min=13},
             };
}
