-----------------------------------------
--
--  T025: BK409B
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1154;
   sat_ypos = 122;
   gemList = {["GBLX"]=9,["GCTX"]=5,["GCLX"]=3,["GCGD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=12},
              [2]={cargo=_G.CARGO_LUXURIES, min=7},
              [3]={cargo=_G.CARGO_GOLD, min=2},
             };
}
