-----------------------------------------
--
--  T026: Atlia II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 438;
   sat_ypos = 496;
}
