-----------------------------------------
--
--  T029: Atlia Sigma
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 569;
   sat_ypos = 339;
   rumor     = 24;
   moves     = 20;
   intel     = 250;
}
