-----------------------------------------
--
--  T030: AS975H
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 237;
   sat_ypos = 369;
   gemList = {["GBLX"]=9,["GCTX"]=9,["GCGD"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=40},
              [2]={cargo=_G.CARGO_GOLD, min=27},
              [3]={cargo=_G.CARGO_ALLOYS, min=13},
             };
}
