-----------------------------------------
--
--  T031: JR881W
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1138;
   sat_ypos = 313;
   gemList = {["GBLX"]=9,["GCTX"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=25},
              [2]={cargo=_G.CARGO_MINERALS, min=18},
              [3]={cargo=_G.CARGO_ALLOYS, min=6},
             };
}
