-----------------------------------------
--
--  T034: Serpens Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 533;
   sat_ypos = 430;
}
