-----------------------------------------
--
--  T035: Serpens VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 805;
   sat_ypos = 213;
}
