-----------------------------------------
--
--  T036: IG253R
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 590;
   sat_ypos = 137;
   gemList = {["GBLX"]=9,["GCGM"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_GEMS, min=35},
              [2]={cargo=_G.CARGO_MINERALS, min=22},
              [3]={cargo=_G.CARGO_ALLOYS, min=11},
             };
}
