-----------------------------------------
--
--  T037: Serpens Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 612;
   sat_ypos = 626;
}
