-----------------------------------------
--
--  T039: Apus VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 941;
   sat_ypos = 246;
}
