-----------------------------------------
--
--  T040: SF793F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 112;
   sat_ypos = 406;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCGD"]=6,["GCLX"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=50},
              [2]={cargo=_G.CARGO_GOLD, min=32},
              [3]={cargo=_G.CARGO_LUXURIES, min=15},
             };
}
