-----------------------------------------
--
--  T041: Apus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 742;
   sat_ypos = 366;
}
