-----------------------------------------
--
--  T042: Gemini IX
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 1111;
   sat_ypos = 322;
}
