-----------------------------------------
--
--  T044: Gemini Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 1025;
   sat_ypos = 466;
}
