-----------------------------------------
--
--  T045: Gemini I
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 603;
   sat_ypos = 572;
}
