-----------------------------------------
--
--  T046: Gemini Labs
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 717;
   sat_ypos = 366;
   rumor     = 10;
   moves     = 15;
   intel     = 100;
}
