-----------------------------------------
--
--  T047: Elea III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 302;
   sat_ypos = 425;
}
