-----------------------------------------
--
--  T048: Elea VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 948;
   sat_ypos = 522;
}
