-----------------------------------------
--
--  T049: Elea Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 956;
   sat_ypos = 161;
}
