-----------------------------------------
--
--  T051: PH549D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 745;
   sat_ypos = 454;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCTK"]=4,["GCTX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=15},
              [2]={cargo=_G.CARGO_TECH, min=10},
              [3]={cargo=_G.CARGO_TEXTILES, min=3},
             };
}
