-----------------------------------------
--
--  T052: Elysia VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 683;
   sat_ypos = 185;
}
