-----------------------------------------
--
--  T053: Elysia IX
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 971;
   sat_ypos = 204;
}
