-----------------------------------------
--
--  T054: Elysia Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 502;
   sat_ypos = 432;
}
