-----------------------------------------
--
--  T055: Port of Elysia
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 779;
   sat_ypos = 388;
}
