-----------------------------------------
--
--  T056: Elysia Lambda
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 947;
   sat_ypos = 530;
   rumor     = 44;
   moves     = 10;
   intel     = 50;
}
