-----------------------------------------
--
--  T057: Vega VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 193;
   sat_ypos = 192;
}
