-----------------------------------------
--
--  T059: JH869T
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 855;
   sat_ypos = 159;
   gemList = {["GBLX"]=9,["GCTX"]=5,["GCFD"]=3,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=10},
              [2]={cargo=_G.CARGO_FOOD, min=6},
              [3]={cargo=_G.CARGO_LUXURIES, min=1},
             };
}
