-----------------------------------------
--
--  T060: Vega Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 595;
   sat_ypos = 304;
}
