-----------------------------------------
--
--  T061: Degani Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 572;
   sat_ypos = 532;
}
