-----------------------------------------
--
--  T063: Degani VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 779;
   sat_ypos = 202;
}
