-----------------------------------------
--
--  T065: Degani Trader
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 546;
   sat_ypos = 145;
   shop_list = import("Satellites/T065_shop");
}
