-----------------------------------------
--
--  T066: Aquarius I
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 507;
   sat_ypos = 507;
}
