-----------------------------------------
--
--  T067: Aquarius IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 819;
   sat_ypos = 398;
}
