-----------------------------------------
--
--  T068: Aquarius Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 583;
   sat_ypos = 260;
}
