-----------------------------------------
--
--  T069: GL398B
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 162;
   sat_ypos = 377;
   gemList = {["GBLX"]=9,["GCFD"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_FOOD, min=30},
              [2]={cargo=_G.CARGO_MINERALS, min=20},
              [3]={cargo=_G.CARGO_ALLOYS, min=8},
             };
}
