-----------------------------------------
--
--  T071: PB943R
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 131;
   sat_ypos = 465;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCAL"]=4,["GCON"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=18},
              [2]={cargo=_G.CARGO_ALLOYS, min=12},
              [3]={cargo=_G.CARGO_CONTRABAND, min=4},
             };
}
