-----------------------------------------
--
--  T072: DH717C
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 508;
   sat_ypos = 500;
   gemList = {["GBLX"]=9,["GCON"]=9,["GCAL"]=6,["GCMD"]=3};
   cargo   = {[1]={cargo=_G.CARGO_CONTRABAND, min=35},
              [2]={cargo=_G.CARGO_ALLOYS, min=22},
              [3]={cargo=_G.CARGO_MEDICINE, min=11},
             };
}
