-----------------------------------------
--
--  T073: Navi Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 656;
   sat_ypos = 399;
}
