-----------------------------------------
--
--  T075: Icarus Alpha
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 704;
   sat_ypos = 363;
   rumor     = 18;
   moves     = 10;
   intel     = 50;
}
