-----------------------------------------
--
--  T076: RJ590M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 364;
   sat_ypos = 325;
   gemList = {["GBLX"]=9,["GCAL"]=9,["GCLX"]=6,["GCMD"]=3};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=30},
              [2]={cargo=_G.CARGO_LUXURIES, min=20},
              [3]={cargo=_G.CARGO_MEDICINE, min=8},
             };
}
