-----------------------------------------
--
--  T077: JR720F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1103;
   sat_ypos = 230;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCLX"]=6,["GCMD"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=35},
              [2]={cargo=_G.CARGO_LUXURIES, min=22},
              [3]={cargo=_G.CARGO_MEDICINE, min=11},
             };
}
