-----------------------------------------
--
--  T078: PB148G
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 164;
   sat_ypos = 201;
   gemList = {["GBLX"]=9,["GCLX"]=6,["GCGD"]=4,["GCMD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_LUXURIES, min=18},
              [2]={cargo=_G.CARGO_GOLD, min=12},
              [3]={cargo=_G.CARGO_MEDICINE, min=4},
             };
}
