-----------------------------------------
--
--  T079: Centauri V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 633;
   sat_ypos = 348;
}
