-----------------------------------------
--
--  T080: Centauri Tradeport
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 294;
   sat_ypos = 200;
}
