-----------------------------------------
--
--  T081: New Antarctika
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 751;
   sat_ypos = 535;
   rumor     = 30;
   moves     = 15;
   intel     = 100;
}
