-----------------------------------------
--
--  T082: Centauri Shipyard
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 831;
   sat_ypos = 156;
   shop_list = import("Satellites/T082_shop");
}
