-----------------------------------------
--
--  T083: BS736Q
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 653;
   sat_ypos = 511;
   gemList = {["GBLX"]=6,["GCMN"]=6,["GCGD"]=6,["GCON"]=6};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=48},
              [2]={cargo=_G.CARGO_GOLD, min=48},
              [3]={cargo=_G.CARGO_CONTRABAND, min=48},
             };
}
