-----------------------------------------
--
--  T084: BK211B
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 899;
   sat_ypos = 452;
   gemList = {["GBLX"]=6,["GCMN"]=6,["GCFD"]=6,["GCGM"]=6};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=48},
              [2]={cargo=_G.CARGO_FOOD, min=48},
              [3]={cargo=_G.CARGO_GEMS, min=48},
             };
}
