-----------------------------------------
--
--  T085: RM371Q
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 865;
   sat_ypos = 278;
   gemList = {["GBLX"]=6,["GCMN"]=6,["GCLX"]=6,["GCGM"]=6};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=48},
              [2]={cargo=_G.CARGO_LUXURIES, min=48},
              [3]={cargo=_G.CARGO_GEMS, min=48},
             };
}
