-----------------------------------------
--
--  T086: PN383X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 591;
   sat_ypos = 288;
   gemList = {["GBLX"]=6,["GCMN"]=6,["GCTK"]=6,["GCLX"]=6};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=48},
              [2]={cargo=_G.CARGO_TECH, min=48},
              [3]={cargo=_G.CARGO_LUXURIES, min=48},
             };
}
