-----------------------------------------
--
--  T087: DT868H
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 339;
   sat_ypos = 219;
   gemList = {["GBLX"]=6,["GCMN"]=6,["GCTX"]=6,["GCTK"]=6};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=48},
              [2]={cargo=_G.CARGO_TEXTILES, min=48},
              [3]={cargo=_G.CARGO_TECH, min=48},
             };
}
