-----------------------------------------
--
--  T088: MD255Q
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 729;
   sat_ypos = 131;
   gemList = {["GBLX"]=6,["GCMN"]=8,["GCTX"]=8,["GCAL"]=8};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=48},
              [2]={cargo=_G.CARGO_TEXTILES, min=48},
              [3]={cargo=_G.CARGO_ALLOYS, min=48},
             };
}
