-----------------------------------------
--
--  T089: New Australis
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 395;
   sat_ypos = 420;
   rumor     = 29;
   moves     = 25;
   intel     = 500;
}
