-----------------------------------------
--
--  T090: Orion VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 900;
   sat_ypos = 230;
}
