-----------------------------------------
--
--  T091: New Europa
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 589;
   sat_ypos = 537;
   rumor     = 2;
   moves     = 5;
   intel     = 25;
}
