-----------------------------------------
--
--  T092: AD508Z
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1177;
   sat_ypos = 365;
   gemList = {["GBLX"]=9,["GCTX"]=6,["GCMN"]=4,["GCAL"]=2};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=18},
              [2]={cargo=_G.CARGO_MINERALS, min=12},
              [3]={cargo=_G.CARGO_ALLOYS, min=4},
             };
}
