-----------------------------------------
--
--  T093: Orion Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 688;
   sat_ypos = 384;
}
