-----------------------------------------
--
--  T095: New Asia
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 666;
   sat_ypos = 183;
   rumor     = 23;
   moves     = 20;
   intel     = 250;
}
