-----------------------------------------
--
--  T096: Lupus Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 446;
   sat_ypos = 456;
}
