-----------------------------------------
--
--  T098: New Amerika
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 277;
   sat_ypos = 330;
   rumor     = 32;
   moves     = 20;
   intel     = 250;
}
