-----------------------------------------
--
--  T099: SR845M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 488;
   sat_ypos = 215;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCTK"]=4,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=20},
              [2]={cargo=_G.CARGO_TECH, min=16},
              [3]={cargo=_G.CARGO_LUXURIES, min=6},
             };
}
