-----------------------------------------
--
--  T100: Aries Shipyard
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 645;
   sat_ypos = 295;
   shop_list = import("Satellites/T100_shop");
}
