-----------------------------------------
--
--  T101: Aquila Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 737;
   sat_ypos = 464;
}
