-----------------------------------------
--
--  T102: New Aztekia
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 567;
   sat_ypos = 442;
   rumor     = 45;
   moves     = 10;
   intel     = 50;
}
