-----------------------------------------
--
--  T103: Ramses III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 945;
   sat_ypos = 493;
}
