-----------------------------------------
--
--  T104: Ramses Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 647;
   sat_ypos = 187;
}
