-----------------------------------------
--
--  T105: DL361X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 175;
   sat_ypos = 169;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCFD"]=6,["GCGM"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=40},
              [2]={cargo=_G.CARGO_FOOD, min=27},
              [3]={cargo=_G.CARGO_GEMS, min=13},
             };
}
