-----------------------------------------
--
--  T106: New Ethiopia
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 830;
   sat_ypos = 215;
   rumor     = 16;
   moves     = 15;
   intel     = 100;
}
