-----------------------------------------
--
--  T107: Sirius Engines
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 666;
   sat_ypos = 491;
   shop_list = import("Satellites/T107_shop");
}
