-----------------------------------------
--
--  T109: NB328Q
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 357;
   sat_ypos = 356;
   gemList = {["GBLX"]=9,["GCTX"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=35},
              [2]={cargo=_G.CARGO_MINERALS, min=22},
              [3]={cargo=_G.CARGO_ALLOYS, min=11},
             };
}
