-----------------------------------------
--
--  T111: PN983Z
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 965;
   sat_ypos = 508;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCAL"]=4,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=20},
              [2]={cargo=_G.CARGO_ALLOYS, min=16},
              [3]={cargo=_G.CARGO_LUXURIES, min=6},
             };
}
