-----------------------------------------
--
--  T112: Circinus II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 677;
   sat_ypos = 466;
}
