-----------------------------------------
--
--  T113: Circinus Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 859;
   sat_ypos = 153;
}
