-----------------------------------------
--
--  T114: Quesada Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 716;
   sat_ypos = 363;
}
