-----------------------------------------
--
--  T115: Quesada Tau
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 607;
   sat_ypos = 183;
   rumor     = 48;
   moves     = 5;
   intel     = 25;
}
