-----------------------------------------
--
--  T116: Quesada Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 1031;
   sat_ypos = 491;
}
