-----------------------------------------
--
--  T117: Hydra Systems
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 1081;
   sat_ypos = 345;
   shop_list = import("Satellites/T117_shop");
}
