-----------------------------------------
--
--  T118: Keck Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 583;
   sat_ypos = 543;
}
