-----------------------------------------
--
--  T119: Keck Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 600;
   sat_ypos = 316;
}
