-----------------------------------------
--
--  T120: Emporium of Keck
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 793;
   sat_ypos = 445;
   shop_list = import("Satellites/T120_shop");
}
