-----------------------------------------
--
--  T121: Altair Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 469;
   sat_ypos = 425;
}
