-----------------------------------------
--
--  T122: Bazaar of Keck
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 551;
   sat_ypos = 191;
   shop_list = import("Satellites/T122_shop");
}
