-----------------------------------------
--
--  T123: JH679R
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 874;
   sat_ypos = 494;
   gemList = {["GBLX"]=9,["GCFD"]=6,["GCAL"]=4,["GCTK"]=2};
   cargo   = {[1]={cargo=_G.CARGO_FOOD, min=18},
              [2]={cargo=_G.CARGO_ALLOYS, min=12},
              [3]={cargo=_G.CARGO_TECH, min=4},
             };
}
