-----------------------------------------
--
--  T124: NB891D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 277;
   sat_ypos = 108;
   gemList = {["GBLX"]=6,["GCAL"]=6,["GCGM"]=6,["GCGD"]=6};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=30},
              [2]={cargo=_G.CARGO_GEMS, min=30},
              [3]={cargo=_G.CARGO_GOLD, min=30},
             };
}
