-----------------------------------------
--
--  T125: Altair V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 708;
   sat_ypos = 363;
}
