-----------------------------------------
--
--  T127: Virgo Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 596;
   sat_ypos = 184;
}
