-----------------------------------------
--
--  T128: Sirius VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 707;
   sat_ypos = 194;
}
