-----------------------------------------
--
--  T129: Sirius Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 467;
   sat_ypos = 420;
}
