-----------------------------------------
--
--  T130: AD758C
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1048;
   sat_ypos = 144;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCON"]=4,["GCMD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=20},
              [2]={cargo=_G.CARGO_CONTRABAND, min=16},
              [3]={cargo=_G.CARGO_MEDICINE, min=6},
             };
}
