-----------------------------------------
--
--  T131: Lepus VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 717;
   sat_ypos = 196;
}
