-----------------------------------------
--
--  T133: Lepus Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 633;
   sat_ypos = 543;
}
