-----------------------------------------
--
--  T135: Tucana V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 625;
   sat_ypos = 344;
}
