-----------------------------------------
--
--  T136: Tucana VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 983;
   sat_ypos = 262;
}
