-----------------------------------------
--
--  T137: Cygnus II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 496;
   sat_ypos = 429;
}
