-----------------------------------------
--
--  T138: Cygnus Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 307;
   sat_ypos = 219;
}
