-----------------------------------------
--
--  T139: PS735C
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 698;
   sat_ypos = 254;
   gemList = {["GBLX"]=9,["GCON"]=9,["GCAL"]=6,["GCMN"]=3};
   cargo   = {[1]={cargo=_G.CARGO_CONTRABAND, min=50},
              [2]={cargo=_G.CARGO_ALLOYS, min=32},
              [3]={cargo=_G.CARGO_MINERALS, min=15},
             };
}
