-----------------------------------------
--
--  T140: Jahrwox Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 678;
   sat_ypos = 357;
}
