-----------------------------------------
--
--  T141: Jahrwox Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 305;
   sat_ypos = 112;
}
