-----------------------------------------
--
--  T142: The Scrapyards
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 1054;
   sat_ypos = 247;
   shop_list = import("Satellites/T142_shop");
}
