-----------------------------------------
--
--  T143: Corvus IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 319;
   sat_ypos = 497;
}
