-----------------------------------------
--
--  T144: Corvus VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 1074;
   sat_ypos = 297;
}
