-----------------------------------------
--
--  T145: Corvus Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 609;
   sat_ypos = 127;
}
