-----------------------------------------
--
--  T146: RJ569M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 740;
   sat_ypos = 325;
   gemList = {["GBLX"]=6,["GCMN"]=8,["GCAL"]=8,["GCTX"]=8};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=35},
              [2]={cargo=_G.CARGO_ALLOYS, min=35},
              [3]={cargo=_G.CARGO_TEXTILES, min=35},
             };
}
