-----------------------------------------
--
--  T147: Pleione VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 915;
   sat_ypos = 451;
}
