-----------------------------------------
--
--  T148: Pleione III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 745;
   sat_ypos = 520;
}
