-----------------------------------------
--
--  T149: Pleione Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 627;
   sat_ypos = 303;
}
