-----------------------------------------
--
--  T150: Pleione Rho
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 458;
   sat_ypos = 165;
   rumor     = 28;
   moves     = 10;
   intel     = 50;
}
