-----------------------------------------
--
--  T151: Cepheus III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 714;
   sat_ypos = 492;
}
