-----------------------------------------
--
--  T152: Cepheus IX
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 954;
   sat_ypos = 250;
}
