-----------------------------------------
--
--  T153: Cepheus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 608;
   sat_ypos = 270;
}
