-----------------------------------------
--
--  T154: Fruits of Cepheus
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 328;
   sat_ypos = 133;
   shop_list = import("Satellites/T154_shop");
}
