-----------------------------------------
--
--  T155: Lyra VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 843;
   sat_ypos = 410;
}
