-----------------------------------------
--
--  T156: Lyra Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 579;
   sat_ypos = 415;
}
