-----------------------------------------
--
--  T157: Lyra Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 554;
   sat_ypos = 178;
   -- rumor    = 0;
   -- moves    = 5;
   intel     = 25;
}
