-----------------------------------------
--
--  T158: Regulus VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 661;
   sat_ypos = 462;
}
