-----------------------------------------
--
--  T159: DH778D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 494;
   sat_ypos = 361;
   gemList = {["GBLX"]=9,["GCTX"]=5,["GCMN"]=3,["GCAL"]=2};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=10},
              [2]={cargo=_G.CARGO_MINERALS, min=6},
              [3]={cargo=_G.CARGO_ALLOYS, min=1},
             };
}
