-----------------------------------------
--
--  T160: Regulus Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 922;
   sat_ypos = 334;
}
