-----------------------------------------
--
--  T161: Theseus IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 702;
   sat_ypos = 355;
}
