-----------------------------------------
--
--  T162: Theseus Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 986;
   sat_ypos = 167;
}
