-----------------------------------------
--
--  T163: BS256D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1026;
   sat_ypos = 510;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCGM"]=6,["GCGD"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=40},
              [2]={cargo=_G.CARGO_GEMS, min=27},
              [3]={cargo=_G.CARGO_GOLD, min=13},
             };
}
