-----------------------------------------
--
--  T164: BK926F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 699;
   sat_ypos = 522;
   gemList = {["GBLX"]=9,["GCGM"]=9,["GCFD"]=6,["GCMN"]=3};
   cargo   = {[1]={cargo=_G.CARGO_GEMS, min=50},
              [2]={cargo=_G.CARGO_FOOD, min=32},
              [3]={cargo=_G.CARGO_MINERALS, min=15},
             };
}
