-----------------------------------------
--
--  T165: Cradle of Quesada
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 352;
   sat_ypos = 141;
   rumor     = 12;
   moves     = 20;
   intel     = 250;
}
