-----------------------------------------
--
--  T168: Cytech Systems
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 747;
   sat_ypos = 137;
   shop_list = import("Satellites/T168_shop");
}
