-----------------------------------------
--
--  T169: Fornax Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 241;
   sat_ypos = 175;
   rumor     = 15;
   moves     = 20;
   intel     = 250;
}
