-----------------------------------------
--
--  T170: Castor V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 725;
   sat_ypos = 364;
}
