-----------------------------------------
--
--  T171: BS584C
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 303;
   sat_ypos = 226;
   gemList = {["GBLX"]=9,["GCAL"]=9,["GCTX"]=6,["GCTK"]=3};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=35},
              [2]={cargo=_G.CARGO_TEXTILES, min=22},
              [3]={cargo=_G.CARGO_TECH, min=11},
             };
}
