-----------------------------------------
--
--  T172: Castor Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 393;
   sat_ypos = 456;
}
