-----------------------------------------
--
--  T173: Castor IX
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 1194;
   sat_ypos = 312;
}
