-----------------------------------------
--
--  T174: Perseus Sigma
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 292;
   sat_ypos = 330;
   rumor     = 27;
   moves     = 20;
   intel     = 250;
}
