-----------------------------------------
--
--  T175: Perseus II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 531;
   sat_ypos = 436;
}
