-----------------------------------------
--
--  T176: Perseus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 494;
   sat_ypos = 147;
}
