-----------------------------------------
--
--  T177: Perseus Engines
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 767;
   sat_ypos = 347;
   shop_list = import("Satellites/T177_shop");
}
