-----------------------------------------
--
--  T178: Auriga X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 839;
   sat_ypos = 221;
}
