-----------------------------------------
--
--  T179: Auriga Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 203;
   sat_ypos = 214;
}
