-----------------------------------------
--
--  T180: JF174M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 740;
   sat_ypos = 478;
   gemList = {["GBLX"]=9,["GCTK"]=9,["GCAL"]=6,["GCMN"]=3};
   cargo   = {[1]={cargo=_G.CARGO_TECH, min=50},
              [2]={cargo=_G.CARGO_ALLOYS, min=32},
              [3]={cargo=_G.CARGO_MINERALS, min=15},
             };
}
