-----------------------------------------
--
--  T182: PS645M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1016;
   sat_ypos = 369;
   gemList = {["GBLX"]=9,["GCTK"]=6,["GCAL"]=4,["GCMN"]=2};
   cargo   = {[1]={cargo=_G.CARGO_TECH, min=25},
              [2]={cargo=_G.CARGO_ALLOYS, min=20},
              [3]={cargo=_G.CARGO_MINERALS, min=8},
             };
}
