-----------------------------------------
--
--  T183: Electra II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 551;
   sat_ypos = 434;
}
