-----------------------------------------
--
--  T184: Robotic Weaponry
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 512;
   sat_ypos = 145;
   shop_list = import("Satellites/T184_shop");
}
