-----------------------------------------
--
--  T185: Electra Zeta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 308;
   sat_ypos = 332;
   rumor     = 26;
   moves     = 25;
   intel     = 500;
}
