-----------------------------------------
--
--  T186: Electra Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 724;
   sat_ypos = 142;
}
