-----------------------------------------
--
--  T187: Sagitta X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 929;
   sat_ypos = 245;
}
