-----------------------------------------
--
--  T188: Sagitta Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 643;
   sat_ypos = 139;
}
