-----------------------------------------
--
--  T189: DL576C
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 139;
   sat_ypos = 279;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCLX"]=4,["GCGD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=25},
              [2]={cargo=_G.CARGO_LUXURIES, min=20},
              [3]={cargo=_G.CARGO_GOLD, min=8},
             };
}
