-----------------------------------------
--
--  T190: BC462X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1163;
   sat_ypos = 397;
   gemList = {["GBLX"]=9,["GCLX"]=5,["GCMN"]=3,["GCFD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_LUXURIES, min=17},
              [2]={cargo=_G.CARGO_MINERALS, min=10},
              [3]={cargo=_G.CARGO_FOOD, min=4},
             };
}
