-----------------------------------------
--
--  T191: MP109R
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 621;
   sat_ypos = 513;
   gemList = {["GBLX"]=9,["GCLX"]=9,["GCAL"]=6,["GCMN"]=3};
   cargo   = {[1]={cargo=_G.CARGO_LUXURIES, min=50},
              [2]={cargo=_G.CARGO_ALLOYS, min=32},
              [3]={cargo=_G.CARGO_MINERALS, min=15},
             };
}
