-----------------------------------------
--
--  T192: Vortraag Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 503;
   sat_ypos = 503;
}
