-----------------------------------------
--
--  T193: Vortraag Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 253;
   sat_ypos = 251;
}
