-----------------------------------------
--
--  T194: Vortraag VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 990;
   sat_ypos = 261;
}
