-----------------------------------------
--
--  T195: Fist of Vortraag
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 582;
   sat_ypos = 341;
   shop_list = import("Satellites/T195_shop");
}
