-----------------------------------------
--
--  T196: Lacerta VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 703;
   sat_ypos = 357;
}
