-----------------------------------------
--
--  T197: Lacerta Omega
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 332;
   sat_ypos = 423;
   rumor     = 42;
   moves     = 15;
   intel     = 100;
}
