-----------------------------------------
--
--  T198: Lacerta Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 1039;
   sat_ypos = 462;
}
