-----------------------------------------
--
--  T199: AC196G
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 633;
   sat_ypos = 144;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCMN"]=4,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=20},
              [2]={cargo=_G.CARGO_MINERALS, min=16},
              [3]={cargo=_G.CARGO_LUXURIES, min=6},
             };
}
