-----------------------------------------
--
--  T200: Aries Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 251;
   sat_ypos = 509;
}
