-----------------------------------------
--
--  T201: Aries Sigma
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 949;
   sat_ypos = 517;
   rumor     = 17;
   moves     = 15;
   intel     = 100;
}
