-----------------------------------------
--
--  T202: Aries Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 357;
   sat_ypos = 103;
}
