-----------------------------------------
--
--  T203: Libra VII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 925;
   sat_ypos = 470;
}
