-----------------------------------------
--
--  T204: Libra Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 768;
   sat_ypos = 247;
}
