-----------------------------------------
--
--  T205: SF973V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1038;
   sat_ypos = 196;
   gemList = {["GBLX"]=6,["GCAL"]=8,["GCMN"]=8,["GCTX"]=8};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=55},
              [2]={cargo=_G.CARGO_MINERALS, min=55},
              [3]={cargo=_G.CARGO_TEXTILES, min=55},
             };
}
