-----------------------------------------
--
--  T206: AD329T
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 637;
   sat_ypos = 383;
   gemList = {["GBLX"]=6,["GCAL"]=6,["GCMN"]=6,["GCTK"]=6};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=48},
              [2]={cargo=_G.CARGO_MINERALS, min=48},
              [3]={cargo=_G.CARGO_TECH, min=48},
             };
}
