-----------------------------------------
--
--  T208: Leo Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 571;
   sat_ypos = 136;
}
