-----------------------------------------
--
--  T209: Leo Omicron
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 919;
   sat_ypos = 245;
   rumor     = 14;
   moves     = 20;
   intel     = 250;
}
