-----------------------------------------
--
--  T210: Leo Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 752;
   sat_ypos = 538;
   rumor     = 36;
   moves     = 15;
   intel     = 100;
}
