-----------------------------------------
--
--  T211: Leo Delta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 463;
   sat_ypos = 495;
   rumor     = 38;
   moves     = 25;
   intel     = 500;
}
