-----------------------------------------
--
--  T212: Taurus I
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 587;
   sat_ypos = 540;
}
