-----------------------------------------
--
--  T213: Taurus IX
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 811;
   sat_ypos = 212;
}
