-----------------------------------------
--
--  T214: Taurus Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 799;
   sat_ypos = 447;
}
