-----------------------------------------
--
--  T215: Musca Weaponry
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 1171;
   sat_ypos = 475;
   shop_list = import("Satellites/T215_shop");
}
