-----------------------------------------
--
--  T216: Indus III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 599;
   sat_ypos = 447;
}
