-----------------------------------------
--
--  T217: Indus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 846;
   sat_ypos = 347;
}
