-----------------------------------------
--
--  T218: Indus Delta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 677;
   sat_ypos = 187;
   rumor     = 3;
   moves     = 10;
   intel     = 50;
}
