-----------------------------------------
--
--  T219: Krystallus Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 622;
   sat_ypos = 179;
}
