-----------------------------------------
--
--  T220: Krystallus Kappa
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 199;
   sat_ypos = 520;
   rumor     = 43;
   moves     = 25;
   intel     = 500;
}
