-----------------------------------------
--
--  T221: Krystallus Delta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 562;
   sat_ypos = 526;
   rumor     = 9;
   moves     = 15;
   intel     = 100;
}
