-----------------------------------------
--
--  T222: Krystallus Iota
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 791;
   sat_ypos = 386;
   rumor     = 13;
   moves     = 20;
   intel     = 250;
}
