-----------------------------------------
--
--  T223: Krystallus Lambda
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 999;
   sat_ypos = 302;
   rumor     = 35;
   moves     = 5;
   intel     = 25;
}
