-----------------------------------------
--
--  T224: Krystallus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 427;
   sat_ypos = 400;
}
