-----------------------------------------
--
--  T225: Megreb I
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 248;
   sat_ypos = 409;
}
