-----------------------------------------
--
--  T226: Megreb Theta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 607;
   sat_ypos = 182;
   rumor     = 40;
   moves     = 10;
   intel     = 50;
}
