-----------------------------------------
--
--  T227: RJ508T
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 323;
   sat_ypos = 282;
   gemList = {["GBLX"]=9,["GCAL"]=6,["GCMN"]=4,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=18},
              [2]={cargo=_G.CARGO_MINERALS, min=12},
              [3]={cargo=_G.CARGO_LUXURIES, min=4},
             };
}
