-----------------------------------------
--
--  T228: Megreb Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 744;
   sat_ypos = 324;
}
