-----------------------------------------
--
--  T229: Eridanus II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 715;
   sat_ypos = 496;
}
