-----------------------------------------
--
--  T230: Eridanus Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 993;
   sat_ypos = 175;
}
