-----------------------------------------
--
--  T231: SC762H
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 324;
   sat_ypos = 217;
   gemList = {["GBLX"]=9,["GCMN"]=5,["GCLX"]=3,["GCAL"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=12},
              [2]={cargo=_G.CARGO_LUXURIES, min=7},
              [3]={cargo=_G.CARGO_ALLOYS, min=2},
             };
}
