-----------------------------------------
--
--  T232: Eridanus Omicron
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 575;
   sat_ypos = 340;
   rumor     = 7;
   moves     = 25;
   intel     = 500;
}
