-----------------------------------------
--
--  T233: Zaurak II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 442;
   sat_ypos = 499;
}
