-----------------------------------------
--
--  T234: Zaurak Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 610;
   sat_ypos = 378;
}
