-----------------------------------------
--
--  T236: MD647X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 473;
   sat_ypos = 131;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCAL"]=6,["GCON"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=35},
              [2]={cargo=_G.CARGO_ALLOYS, min=22},
              [3]={cargo=_G.CARGO_CONTRABAND, min=11},
             };
}
