-----------------------------------------
--
--  T237: Plasmia Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 592;
   sat_ypos = 444;
}
