-----------------------------------------
--
--  T238: Plasmia Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 836;
   sat_ypos = 497;
}
