-----------------------------------------
--
--  T239: Plasmia Theta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 867;
   sat_ypos = 228;
   rumor     = 46;
   moves     = 15;
   intel     = 100;
}
