-----------------------------------------
--
--  T240: Delphinus VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 1054;
   sat_ypos = 293;
}
