-----------------------------------------
--
--  T241: Delphinus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 549;
   sat_ypos = 507;
}
