-----------------------------------------
--
--  T242: Delphinus V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 377;
   sat_ypos = 168;
}
