-----------------------------------------
--
--  T243: BS719F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 697;
   sat_ypos = 388;
   gemList = {["GBLX"]=6,["GCTX"]=8,["GCMN"]=8,["GCFD"]=8};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=55},
              [2]={cargo=_G.CARGO_MINERALS, min=55},
              [3]={cargo=_G.CARGO_FOOD, min=55},
             };
}
