-----------------------------------------
--
--  T244: Pegasus VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 845;
   sat_ypos = 216;
}
