-----------------------------------------
--
--  T245: Pegasus Kappa
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 338;
   sat_ypos = 423;
   -- rumor    = 0; 
   -- moves    = 5; 
   intel     = 25;
}
