-----------------------------------------
--
--  T246: Pegasus Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 784;
   sat_ypos = 424;
}
