-----------------------------------------
--
--  T247: Hydra VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 289;
   sat_ypos = 332;
}
