-----------------------------------------
--
--  T248: Hydra VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 869;
   sat_ypos = 222;
}
