-----------------------------------------
--
--  T249: Hydra Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 607;
   sat_ypos = 150;
}
