-----------------------------------------
--
--  T250: DT347D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 864;
   sat_ypos = 492;
   gemList = {["GBLX"]=9,["GCTX"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=35},
              [2]={cargo=_G.CARGO_MINERALS, min=22},
              [3]={cargo=_G.CARGO_ALLOYS, min=11},
             };
}
