-----------------------------------------
--
--  T251: Carinox Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 940;
   sat_ypos = 210;
}
