-----------------------------------------
--
--  T252: Carinox VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 509;
   sat_ypos = 173;
}
