-----------------------------------------
--
--  T253: KG813M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 319;
   sat_ypos = 439;
   gemList = {["GBLX"]=9,["GCTX"]=6,["GCMN"]=4,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_TEXTILES, min=20},
              [2]={cargo=_G.CARGO_MINERALS, min=16},
              [3]={cargo=_G.CARGO_LUXURIES, min=6},
             };
}
