-----------------------------------------
--
--  T254: BC320V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 710;
   sat_ypos = 293;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCGM"]=4,["GCFD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=25},
              [2]={cargo=_G.CARGO_GEMS, min=20},
              [3]={cargo=_G.CARGO_FOOD, min=8},
             };
}
