-----------------------------------------
--
--  T255: Scorpio Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 713;
   sat_ypos = 165;
}
