-----------------------------------------
--
--  T256: Scorpio III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 660;
   sat_ypos = 460;
}
