-----------------------------------------
--
--  T257: Scorpio Theta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 506;
   sat_ypos = 333;
   rumor     = 4;
   moves     = 15;
   intel     = 100;
}
