-----------------------------------------
--
--  T258: AD356Z
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 295;
   sat_ypos = 220;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCTX"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=40},
              [2]={cargo=_G.CARGO_TEXTILES, min=27},
              [3]={cargo=_G.CARGO_ALLOYS, min=13},
             };
}
