-----------------------------------------
--
--  T259: Gomorrah Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 855;
   sat_ypos = 178;
}
