-----------------------------------------
--
--  T260: Gomorrah IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 690;
   sat_ypos = 475;
}
