-----------------------------------------
--
--  T261: Gomorrah Phi
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 286;
   sat_ypos = 169;
   rumor     = 19;
   moves     = 25;
   intel     = 500;
}
