-----------------------------------------
--
--  T262: Solis Prison
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 621;
   sat_ypos = 263;
}
