-----------------------------------------
--
--  T263: Solis Mine
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 600;
   sat_ypos = 553;
   rumor     = 11;
   moves     = 25;
   intel     = 500;
}
