-----------------------------------------
--
--  T264: Solis II
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 381;
   sat_ypos = 420;
}
