-----------------------------------------
--
--  T265: AC516H
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 915;
   sat_ypos = 298;
   gemList = {["GBLX"]=6,["GCMN"]=8,["GCAL"]=8,["GCTX"]=8};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=55},
              [2]={cargo=_G.CARGO_ALLOYS, min=55},
              [3]={cargo=_G.CARGO_TEXTILES, min=55},
             };
}
