-----------------------------------------
--
--  T266: MS578F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 241;
   sat_ypos = 220;
   gemList = {["GBLX"]=9,["GCLX"]=5,["GCON"]=3,["GCGD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_LUXURIES, min=17},
              [2]={cargo=_G.CARGO_CONTRABAND, min=10},
              [3]={cargo=_G.CARGO_GOLD, min=4},
             };
}
