-----------------------------------------
--
--  T267: Procyon X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 356;
   sat_ypos = 166;
}
