-----------------------------------------
--
--  T268: RM911M
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 829;
   sat_ypos = 484;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCFD"]=4,["GCMD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=20},
              [2]={cargo=_G.CARGO_FOOD, min=16},
              [3]={cargo=_G.CARGO_MEDICINE, min=6},
             };
}
