-----------------------------------------
--
--  T269: Procyon Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 468;
   sat_ypos = 425;
   rumor     = 8;
   moves     = 20;
   intel     = 250;
}
