-----------------------------------------
--
--  T271: Fires of Azha
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 915;
   sat_ypos = 179;
   shop_list = import("Satellites/T271_shop");
}
