-----------------------------------------
--
--  T273: Azha Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 447;
   sat_ypos = 453;
}
