-----------------------------------------
--
--  T274: DH577R
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 345;
   sat_ypos = 232;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCAL"]=4,["GCTK"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=20},
              [2]={cargo=_G.CARGO_ALLOYS, min=16},
              [3]={cargo=_G.CARGO_TECH, min=6},
             };
}
