-----------------------------------------
--
--  T275: Sargon VIII
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 658;
   sat_ypos = 193;
}
