-----------------------------------------
--
--  T276: JR206G
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 880;
   sat_ypos = 506;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCMD"]=4,["GCON"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=25},
              [2]={cargo=_G.CARGO_MEDICINE, min=20},
              [3]={cargo=_G.CARGO_CONTRABAND, min=8},
             };
}
