-----------------------------------------
--
--  T277: RM391Z
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 969;
   sat_ypos = 301;
   gemList = {["GBLX"]=9,["GCMD"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MEDICINE, min=50},
              [2]={cargo=_G.CARGO_MINERALS, min=32},
              [3]={cargo=_G.CARGO_ALLOYS, min=15},
             };
}
