-----------------------------------------
--
--  T278: Sargon Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 380;
   sat_ypos = 394;
}
