-----------------------------------------
--
--  T279: Nashira Port
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 644;
   sat_ypos = 314;
}
