-----------------------------------------
--
--  T280: Nashira Lambda
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 737;
   sat_ypos = 508;
   rumor     = 21;
   moves     = 30;
   intel     = 1000;
}
