-----------------------------------------
--
--  T281: Nashira V
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 467;
   sat_ypos = 502;
}
