-----------------------------------------
--
--  T283: Vela Base
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 640;
   sat_ypos = 507;
}
