-----------------------------------------
--
--  T284: Rogue Systems
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SHYD";
   sat_xpos = 645;
   sat_ypos = 260;
   shop_list = import("Satellites/T284_shop");
}
