-----------------------------------------
--
--  T285: Nornes Station
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "SPST";
   sat_xpos = 391;
   sat_ypos = 228;
}
