-----------------------------------------
--
--  T286: Nornes IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 857;
   sat_ypos = 417;
}
