-----------------------------------------
--
--  T287: Nornes I
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 601;
   sat_ypos = 557;
}
