-----------------------------------------
--
--  T288: Nornes III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 483;
   sat_ypos = 426;
}
