-----------------------------------------
--
--  T289: Nornes VI
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 742;
   sat_ypos = 197;
}
