-----------------------------------------
--
--  T290: Gehenna III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 622;
   sat_ypos = 373;
}
