-----------------------------------------
--
--  T291: Gehenna IV
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 898;
   sat_ypos = 195;
}
