-----------------------------------------
--
--  T292: PN366W
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 303;
   sat_ypos = 230;
   gemList = {["GBLX"]=9,["GCFD"]=6,["GCTK"]=4,["GCGD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_FOOD, min=25},
              [2]={cargo=_G.CARGO_TECH, min=20},
              [3]={cargo=_G.CARGO_GOLD, min=8},
             };
}
