-----------------------------------------
--
--  T293: Gehenna Omega
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 934;
   sat_ypos = 473;
   rumor     = 39;
   moves     = 25;
   intel     = 500;
}
