-----------------------------------------
--
--  T294: Typhon X
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 891;
   sat_ypos = 172;
}
