-----------------------------------------
--
--  T295: Typhon Delta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 344;
   sat_ypos = 261;
   rumor     = 25;
   moves     = 20;
   intel     = 250;
}
