-----------------------------------------
--
--  T296: MP937B
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 638;
   sat_ypos = 509;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCTK"]=4,["GCLX"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=25},
              [2]={cargo=_G.CARGO_TECH, min=20},
              [3]={cargo=_G.CARGO_LUXURIES, min=8},
             };
}
