-----------------------------------------
--
--  T297: Typhon Rho
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 612;
   sat_ypos = 208;
   rumor     = 31;
   moves     = 10;
   intel     = 50;
}
