-----------------------------------------
--
--  T298: SR487Z
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 702;
   sat_ypos = 486;
   gemList = {["GBLX"]=9,["GCMN"]=6,["GCLX"]=4,["GCMD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=20},
              [2]={cargo=_G.CARGO_LUXURIES, min=16},
              [3]={cargo=_G.CARGO_MEDICINE, min=6},
             };
}
