-----------------------------------------
--
--  T299: KG740W
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1040;
   sat_ypos = 492;
   gemList = {["GBLX"]=9,["GCFD"]=5,["GCGM"]=3,["GCMD"]=2};
   cargo   = {[1]={cargo=_G.CARGO_FOOD, min=17},
              [2]={cargo=_G.CARGO_GEMS, min=10},
              [3]={cargo=_G.CARGO_MEDICINE, min=4},
             };
}
