-----------------------------------------
--
--  T302: PB849B
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 325;
   sat_ypos = 389;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCAL"]=6,["GCON"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=40},
              [2]={cargo=_G.CARGO_ALLOYS, min=27},
              [3]={cargo=_G.CARGO_CONTRABAND, min=13},
             };
}
