-----------------------------------------
--
--  T303: BK371F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 862;
   sat_ypos = 197;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCON"]=6,["GCGD"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=30},
              [2]={cargo=_G.CARGO_CONTRABAND, min=20},
              [3]={cargo=_G.CARGO_GOLD, min=8},
             };
}
