-----------------------------------------
--
--  T304: Gorgon III
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 524;
   sat_ypos = 171;
}
