-----------------------------------------
--
--  T305: Acheron Prime
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "PLNT";
   sat_xpos = 611;
   sat_ypos = 446;
}
