-----------------------------------------
--
--  T306: Musca Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 346;
   sat_ypos = 168;
   rumor     = 34;
   moves     = 25;
   intel     = 500;
}
