-----------------------------------------
--
--  T308: MD540Z
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 806;
   sat_ypos = 500;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCGD"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=40},
              [2]={cargo=_G.CARGO_GOLD, min=27},
              [3]={cargo=_G.CARGO_ALLOYS, min=13},
             };
}
