-----------------------------------------
--
--  T310: Medusa Alpha
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 848;
   sat_ypos = 218;
   rumor     = 5;
   moves     = 5;
   intel     = 25;
}
