-----------------------------------------
--
--  T311: IG199D
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 526;
   sat_ypos = 101;
   gemList = {["GBLX"]=9,["GCAL"]=9,["GCMN"]=6,["GCON"]=3};
   cargo   = {[1]={cargo=_G.CARGO_ALLOYS, min=40},
              [2]={cargo=_G.CARGO_MINERALS, min=27},
              [3]={cargo=_G.CARGO_CONTRABAND, min=13},
             };
}
