-----------------------------------------
--
--  T314: MD775F
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 1041;
   sat_ypos = 342;
   gemList = {["GBLX"]=9,["GCMN"]=9,["GCAL"]=6,["GCTX"]=3};
   cargo   = {[1]={cargo=_G.CARGO_MINERALS, min=40},
              [2]={cargo=_G.CARGO_ALLOYS, min=27},
              [3]={cargo=_G.CARGO_TEXTILES, min=13},
             };
}
