-----------------------------------------
--
--  T315: Keck Sigma
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 351;
   sat_ypos = 167;
   rumor     = 47;
   moves     = 15;
   intel     = 100;
}
