-----------------------------------------
--
--  T316: Vela Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 349;
   sat_ypos = 173;
   rumor     = 37;
   moves     = 10;
   intel     = 50;
}
