-----------------------------------------
--
--  T317: Sargon Pi
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 785;
   sat_ypos = 382;
   rumor     = 49;
   moves     = 10;
   intel     = 50;
}
