-----------------------------------------
--
--  T318: Corvus Lambda
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 634;
   sat_ypos = 634;
   rumor     = 41;
   moves     = 15;
   intel     = 100;
}
