-----------------------------------------
--
--  T319: Carinox Gamma
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 653;
   sat_ypos = 461;
   rumor     = 20;
   moves     = 20;
   intel     = 250;
}
