-----------------------------------------
--
--  T320: Sagitta Theta
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 521;
   sat_ypos = 336;
   rumor     = 6;
   moves     = 20;
   intel     = 250;
}
