-----------------------------------------
--
--  T321: Zaurak Omega
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 947;
   sat_ypos = 495;
   rumor     = 1;
   moves     = 15;
   intel     = 100;
}
