-----------------------------------------
--
--  T322: Circinus Pi
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 540;
   sat_ypos = 662;
   rumor     = 33;
   moves     = 30;
   intel     = 1000;
}
