-----------------------------------------
--
--  T323: Quaris Epsilon
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 924;
   sat_ypos = 466;
   rumor     = 22;
   moves     = 5;
   intel     = 25;
}
