-----------------------------------------
--
--  T324: Elea Tau
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "MOON";
   sat_xpos = 417;
   sat_ypos = 169;
   rumor     = 0;
   moves     = 5;
   intel     = 25;
}
