-----------------------------------------
--
--  T325: GW656Q
--
--  This file is autogenerated by <StarSystem Editor.exe>
--

return {
   id_type  = "ASTD";
   sat_xpos = 906;
   sat_ypos = 152;
   gemList = {["GBLX"]=9,["GCGD"]=9,["GCMN"]=6,["GCAL"]=3};
   cargo   = {[1]={cargo=_G.CARGO_GOLD, min=50},
              [2]={cargo=_G.CARGO_MINERALS, min=32},
              [3]={cargo=_G.CARGO_ALLOYS, min=15},
             };
}
